import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';

export class GodDomainTable extends Table {
	constructor() {
		let entries = [] as TableEntry[];
		entries.push(new TableEntry('storms'));
		entries.push(new TableEntry('knowledge'));
		entries.push(new TableEntry('fire'));
		entries.push(new TableEntry('earth'));
		entries.push(new TableEntry('night'));
		entries.push(new TableEntry('life'));
		entries.push(new TableEntry('shadows'));
		entries.push(new TableEntry('justice'));
		entries.push(new TableEntry('stars'));
		entries.push(new TableEntry('sky'));
		entries.push(new TableEntry('protection'));
		entries.push(new TableEntry('harvest'));
		entries.push(new TableEntry('hunting'));
		entries.push(new TableEntry('sun'));
		entries.push(new TableEntry('disease'));
		entries.push(new TableEntry('craft'));
		entries.push(new TableEntry('winter'));
		entries.push(new TableEntry('oceans'));
		entries.push(new TableEntry('wisdom'));
		entries.push(new TableEntry('secrets'));
		entries.push(new TableEntry('dance'));
		entries.push(new TableEntry('lost souls'));
		entries.push(new TableEntry('darkness'));
		entries.push(new TableEntry('nature'));
		entries.push(new TableEntry('fortune'));
		entries.push(new TableEntry('vigilance'));
		entries.push(new TableEntry('the depths'));
		entries.push(new TableEntry('change'));
		entries.push(new TableEntry('prophecy'));
		entries.push(new TableEntry('cosmos'));
		entries.push(new TableEntry('war'));
		entries.push(new TableEntry('gateways'));
		entries.push(new TableEntry('time'));
		entries.push(new TableEntry('creation'));
		entries.push(new TableEntry('soul'));
		entries.push(new TableEntry('dreams'));
		entries.push(new TableEntry('battle'));
		entries.push(new TableEntry('magic'));
		entries.push(new TableEntry('wealth'));
		entries.push(new TableEntry('strength'));
		entries.push(new TableEntry('love'));
		entries.push(new TableEntry('travel'));
		entries.push(new TableEntry('fertility'));
		entries.push(new TableEntry('beauty'));
		entries.push(new TableEntry('music'));
		entries.push(new TableEntry('craftsmanship'));
		entries.push(new TableEntry('agriculture'));
		entries.push(new TableEntry('healing'));
		entries.push(new TableEntry('death'));
		entries.push(new TableEntry('rebirth'));
		entries.push(new TableEntry('trade'));
		entries.push(new TableEntry('trickery'));
		entries.push(new TableEntry('peace'));
		entries.push(new TableEntry('chaos'));
		entries.push(new TableEntry('light'));
		entries.push(new TableEntry('balance'));
		entries.push(new TableEntry('animals'));
		entries.push(new TableEntry('ancestors'));
		entries.push(new TableEntry('vengeance'));
		entries.push(new TableEntry('honor'));
		entries.push(new TableEntry('fate'));
		entries.push(new TableEntry('sacrifice'));
		entries.push(new TableEntry('freedom'));
		entries.push(new TableEntry('joy'));
		entries.push(new TableEntry('despair'));
		entries.push(new TableEntry('illusion'));
		entries.push(new TableEntry('victory'));
		entries.push(new TableEntry('invention'));
		super(entries, TableTitles.GodDomain);
		this.tableType = TableType.Other;
	}
}
