import { Entity } from '../base/entity';
import { TechManager } from '$lib/simulation/managers/TechManager';
import { PolicyManager } from '$lib/simulation/managers/PolicyManager';
import { DiplomacyManager } from '$lib/simulation/managers/DiplomacyManager';
import { TerrainType } from './terrainType';

/**
 * Diplomacy state between two nations
 */
export enum DiplomacyState {
	Peace = 'peace',
	War = 'war',
	Alliance = 'alliance',
	Trade = 'trade',
	Neutral = 'neutral',
	Hostile = 'hostile',
	Friendly = 'friendly'
}

/**
 * Diplomacy relationship with another nation
 */
export interface DiplomacyRelationship {
	targetNationId: string;
	state: DiplomacyState;
	opinion: number; // -100 to +100
	treatySince?: number; // Year treaty started
	warsSince?: number; // Year war started
	tradeSince?: number; // Year trade agreement started
	lastInteraction?: number; // Year of last diplomatic action
	grievances: string[]; // List of active grievances
	diplomaticHistory: Array<{
		year: number;
		action: string;
		description: string;
	}>;
}

/**
 * Culture traits that affect AI behavior (Civ 5 inspired)
 * Each trait is on a 0-100 scale
 */
export interface CultureTraits {
	militaristic: number; // Tendency toward military buildup and conquest
	expansionist: number; // Desire to settle new cities and claim territory
	commercial: number; // Focus on trade and economic development
	scientific: number; // Emphasis on technology research
	seafaring: number; // Preference for naval units and coastal expansion
	diplomatic: number; // Tendency to form alliances and avoid conflict
}

/**
 * Resource accumulation and yields (Civ 5 style)
 */
export interface NationResources {
	food: number; // Surplus food (for growth and trade)
	production: number; // Production capacity (for units/buildings)
	gold: number; // Accumulated gold (for purchases and maintenance)
	science: number; // Science per turn (for tech progress)
	culture: number; // Culture per turn (for policies and borders)
	happiness: number; // Total happiness (-100 to +100)
}

/**
 * Era progression (Civ 5 eras)
 */
export enum Era {
	Prehistoric = 'prehistoric',
	Ancient = 'ancient',
	Classical = 'classical',
	Medieval = 'medieval',
	Renaissance = 'renaissance',
	Industrial = 'industrial',
	Modern = 'modern',
	Atomic = 'atomic',
	Information = 'information'
}

/**
 * Enhanced Nation entity with full Civilization 5-style simulation
 */
export class Nation extends Entity {
	// Basic properties (legacy)
	name = '';
	description = '';
	adjective = '';

	// === MODE FLAG (Phase 3.2: Nation Dual-Mode Support) ===
	/**
	 * Determines whether this nation was generated by simulation or created manually for RPG purposes
	 * - false: RPG mode (manually created, simple narrative properties)
	 * - true: Simulation mode (generated by SimulationEngine, full mechanics)
	 */
	isSimulationGenerated = false;

	// === RPG MODE PROPERTIES (only used when isSimulationGenerated = false) ===
	/**
	 * Technology level for RPG nations (from old NationCreator)
	 * Examples: 'Stone Age', 'Bronze Age', 'Medieval', 'Renaissance', 'Industrial'
	 */
	technologyLevel?: string;

	/**
	 * Landscape/terrain preference description (for RPG mode display)
	 * Examples: 'mountains', 'forests', 'desert', 'coastal', 'plains'
	 */
	landscape?: string;

	/**
	 * Preferred terrain types for starting location (simulation mode)
	 * Nation's settler will be placed on one of these terrain types if available
	 */
	preferredTerrainTypes: TerrainType[] = [TerrainType.Grass, TerrainType.Plains];

	/**
	 * Primary resource for RPG nations (from old NationCreator)
	 * Examples: 'gold', 'iron', 'timber', 'fish', 'spices'
	 */
	primaryResource?: string;

	/**
	 * Population size category for RPG nations (from old NationCreator)
	 * Examples: 'small', 'medium', 'large', 'vast'
	 */
	populationSize?: string;

	/**
	 * Government type for RPG nations (from old NationCreator)
	 * Examples: 'monarchy', 'republic', 'theocracy', 'tribal council'
	 * Note: Simulation mode uses governmentType property instead
	 */
	government?: string;

	// Racial and cultural identity
	race = ''; // Human, Elf, Dwarf, Orc, etc. (fantasy mode) or ethnic group (realistic mode)
	culturalIdentity = ''; // Celtic, Roman, Chinese, etc.
	foundingYear = -10000; // When this nation was founded

	// Leadership
	leaderName = ''; // Current leader's name
	leaderTitle = 'Chief'; // Chief, King, Emperor, President, etc.
	governmentType = 'Tribal'; // Tribal, Monarchy, Republic, Democracy, etc.

	// Territory and cities
	capitalCityId?: string; // ID of the capital city
	cityIds: string[] = []; // IDs of all cities controlled by this nation
	territoryHexIds: string[] = []; // IDs of all RegionalHexTile entities owned
	territorySize = 0; // Number of hex tiles controlled

	// Population
	totalPopulation = 1000; // Total population across all cities
	populationGrowthRate = 0; // Current growth rate

	// Managers (Unciv-inspired separation of concerns)
	techManager: TechManager;
	policyManager: PolicyManager;
	diplomacyManagers: Map<string, DiplomacyManager> = new Map(); // One per other nation

	// Resources (Civ 5 style)
	resources: NationResources = {
		food: 0,
		production: 0,
		gold: 0,
		science: 0,
		culture: 0,
		happiness: 0
	};

	// Per-turn yields
	yields: NationResources = {
		food: 0,
		production: 0,
		gold: 2,
		science: 0,
		culture: 0,
		happiness: 0
	};

	// Technology (Civ 5 tech tree)
	currentEra: Era = Era.Prehistoric;
	discoveredTechs: string[] = []; // IDs of unlocked technologies
	currentResearch?: string; // Tech currently being researched
	researchProgress = 0; // Beakers accumulated toward current tech
	sciencePerTurn = 0; // Science generated per turn

	// Culture and Social Policies (Civ 5 policies)
	cultureAccumulated = 0; // Total culture accumulated
	culturePerTurn = 0; // Culture generated per turn
	unlockedPolicies: string[] = []; // IDs of unlocked social policies
	unlockedPolicyTrees: string[] = []; // Which policy trees are unlocked

	// Culture traits (affects AI behavior)
	cultureTraits: CultureTraits = {
		militaristic: 50,
		expansionist: 50,
		commercial: 50,
		scientific: 50,
		seafaring: 50,
		diplomatic: 50
	};

	// Military
	militaryUnits: string[] = []; // IDs of military units
	militaryStrength = 0; // Total military power
	armies: string[] = []; // IDs of Army entities
	fleets: string[] = []; // IDs of Fleet entities

	// Diplomacy
	diplomacyRelationships: Map<string, DiplomacyRelationship> = new Map();
	alliedNations: string[] = []; // IDs of allied nations
	atWarWith: string[] = []; // IDs of nations at war with
	tradePartners: string[] = []; // IDs of nations with trade agreements

	// Historical tracking
	historicalEventIds: string[] = []; // All events involving this nation
	battlesParticipated: string[] = []; // IDs of battles this nation fought
	citiesFounded: Array<{ cityId: string; year: number }> = [];
	leadersHistory: Array<{ name: string; title: string; fromYear: number; toYear: number | null }> = [];

	// Strategic resources (Civ 5 resources)
	strategicResources: Map<string, number> = new Map(); // Iron: 5, Horses: 3, etc.
	luxuryResources: Map<string, number> = new Map(); // Gold: 2, Gems: 1, etc.

	// Status
	isActive = true; // Whether nation still exists
	isAIControlled = true; // Whether controlled by AI
	isEliminated = false; // Whether nation has been destroyed
	eliminatedYear?: number; // Year nation was eliminated

	// Parent references
	parentPlanetId = ''; // Planet this nation exists on

	// Starting position (for settler placement)
	startingHexX?: number; // Global X coordinate of starting position
	startingHexY?: number; // Global Y coordinate of starting position
	hasFoundedFirstCity = false; // Whether the settler has founded the first city

	// Modifiers and bonuses
	happinessModifiers: Array<{ source: string; value: number }> = [];
	goldModifiers: Array<{ source: string; value: number }> = [];
	scienceModifiers: Array<{ source: string; value: number }> = [];

	constructor() {
		super();

		// Initialize managers
		this.techManager = new TechManager();
		this.policyManager = new PolicyManager();
		// DiplomacyManagers are created on-demand when meeting other nations

		this.initializeLeader();
	}

	/**
	 * Initialize the founding leader
	 */
	private initializeLeader(): void {
		if (!this.leaderName) {
			this.leaderName = 'Founder';
		}
		this.leadersHistory.push({
			name: this.leaderName,
			title: this.leaderTitle,
			fromYear: this.foundingYear,
			toYear: null
		});
	}

	/**
	 * Get or create DiplomacyManager for another nation
	 */
	getDiplomacyManager(nationId: string, nationName: string): DiplomacyManager {
		let manager = this.diplomacyManagers.get(nationId);
		if (!manager) {
			manager = new DiplomacyManager(nationId, nationName);
			this.diplomacyManagers.set(nationId, manager);
		}
		return manager;
	}

	/**
	 * Process one turn for all managers
	 */
	processTurn(currentTurn: number): {
		techCompleted: boolean;
		techId?: string;
		policyReady: boolean;
	} {
		// Process tech research
		const techCost = this.techManager.currentTechCost ?? 100; // Use stored cost or fallback to 100
		const techResult = this.techManager.processTurn(this.sciencePerTurn, techCost);

		// Sync to legacy properties
		if (techResult.completed && techResult.techId) {
			this.discoveredTechs.push(techResult.techId);
			this.currentResearch = undefined;
			this.researchProgress = 0;
		}
		this.discoveredTechs = [...this.techManager.researchedTechs];
		this.currentResearch = this.techManager.currentResearch;
		this.researchProgress = this.techManager.researchProgress;
		this.currentEra = this.techManager.currentEra;

		// Process policy accumulation
		this.policyManager.processTurn(this.culturePerTurn);

		// Sync to legacy properties
		this.unlockedPolicies = [...this.policyManager.unlockedPolicies];
		this.cultureAccumulated = this.policyManager.cultureStored + this.policyManager.totalCultureGenerated;

		// Process diplomacy decay for all known nations
		for (const [, manager] of this.diplomacyManagers) {
			manager.processTurnDecay(currentTurn);
		}

		return {
			techCompleted: techResult.completed,
			techId: techResult.techId,
			policyReady: this.policyManager.canAffordPolicy()
		};
	}

	/**
	 * Get diplomacy state with another nation
	 */
	getDiplomacyState(nationId: string): DiplomacyState {
		return this.diplomacyRelationships.get(nationId)?.state || DiplomacyState.Neutral;
	}

	/**
	 * Set diplomacy state with another nation
	 */
	setDiplomacyState(nationId: string, state: DiplomacyState, year: number): void {
		const existing = this.diplomacyRelationships.get(nationId);

		if (existing) {
			existing.state = state;
			existing.lastInteraction = year;
			existing.diplomaticHistory.push({
				year,
				action: state,
				description: `Relations changed to ${state}`
			});
		} else {
			this.diplomacyRelationships.set(nationId, {
				targetNationId: nationId,
				state,
				opinion: 0,
				treatySince: state === DiplomacyState.Alliance ? year : undefined,
				warsSince: state === DiplomacyState.War ? year : undefined,
				tradeSince: state === DiplomacyState.Trade ? year : undefined,
				lastInteraction: year,
				grievances: [],
				diplomaticHistory: [{
					year,
					action: state,
					description: `Initial relations: ${state}`
				}]
			});
		}

		// Update related arrays
		if (state === DiplomacyState.Alliance && !this.alliedNations.includes(nationId)) {
			this.alliedNations.push(nationId);
		} else if (state !== DiplomacyState.Alliance) {
			this.alliedNations = this.alliedNations.filter(id => id !== nationId);
		}

		if (state === DiplomacyState.War && !this.atWarWith.includes(nationId)) {
			this.atWarWith.push(nationId);
		} else if (state !== DiplomacyState.War) {
			this.atWarWith = this.atWarWith.filter(id => id !== nationId);
		}

		if (state === DiplomacyState.Trade && !this.tradePartners.includes(nationId)) {
			this.tradePartners.push(nationId);
		} else if (state !== DiplomacyState.Trade) {
			this.tradePartners = this.tradePartners.filter(id => id !== nationId);
		}
	}

	/**
	 * Get opinion of another nation (-100 to +100)
	 */
	getOpinion(nationId: string): number {
		return this.diplomacyRelationships.get(nationId)?.opinion || 0;
	}

	/**
	 * Modify opinion of another nation
	 */
	modifyOpinion(nationId: string, delta: number, reason: string): void {
		const relationship = this.diplomacyRelationships.get(nationId);
		if (relationship) {
			relationship.opinion = Math.max(-100, Math.min(100, relationship.opinion + delta));
			if (delta !== 0) {
				relationship.grievances.push(reason);
			}
		}
	}

	/**
	 * Check if at war with another nation
	 */
	isAtWarWith(nationId: string): boolean {
		return this.atWarWith.includes(nationId);
	}

	/**
	 * Check if allied with another nation
	 */
	isAlliedWith(nationId: string): boolean {
		return this.alliedNations.includes(nationId);
	}

	/**
	 * Add a discovered technology
	 */
	discoverTech(techId: string, year: number): void {
		if (!this.discoveredTechs.includes(techId)) {
			this.discoveredTechs.push(techId);
			// Update era based on techs (will be implemented with tech tree)
		}
	}

	/**
	 * Check if a technology is discovered
	 */
	hasTech(techId: string): boolean {
		return this.discoveredTechs.includes(techId);
	}

	/**
	 * Unlock a social policy
	 */
	unlockPolicy(policyId: string): void {
		if (!this.unlockedPolicies.includes(policyId)) {
			this.unlockedPolicies.push(policyId);
		}
	}

	/**
	 * Add a city to this nation
	 */
	addCity(cityId: string, year: number, isCapital = false): void {
		if (!this.cityIds.includes(cityId)) {
			this.cityIds.push(cityId);
			this.citiesFounded.push({ cityId, year });

			if (isCapital || !this.capitalCityId) {
				this.capitalCityId = cityId;
			}
		}
	}

	/**
	 * Remove a city (conquered or destroyed)
	 */
	removeCity(cityId: string): void {
		this.cityIds = this.cityIds.filter(id => id !== cityId);
		if (this.capitalCityId === cityId) {
			// Set new capital to first remaining city
			this.capitalCityId = this.cityIds[0];
		}
	}

	/**
	 * Calculate total military strength
	 */
	calculateMilitaryStrength(): number {
		// Will be implemented with unit system
		return this.militaryUnits.length * 10;
	}

	/**
	 * Update per-turn yields from all cities and sources
	 */
	updateYields(): void {
		// Will be implemented with city and yield calculation system
		this.sciencePerTurn = this.yields.science;
		this.culturePerTurn = this.yields.culture;
	}

	/**
	 * Eliminate this nation
	 */
	eliminate(year: number): void {
		this.isEliminated = true;
		this.isActive = false;
		this.eliminatedYear = year;

		// End current leader's reign
		const currentLeader = this.leadersHistory[this.leadersHistory.length - 1];
		if (currentLeader && currentLeader.toYear === null) {
			currentLeader.toYear = year;
		}
	}

	/**
	 * Get a summary of this nation's status
	 */
	getSummary(): string {
		const cityCount = this.cityIds.length;
		const population = this.totalPopulation.toLocaleString();
		const eraName = this.currentEra;
		const status = this.isEliminated ? '(Eliminated)' : this.isActive ? '(Active)' : '(Inactive)';

		return `${this.name} ${status}: ${cityCount} cities, ${population} population, ${eraName} era`;
	}
}
