import { Creator } from '../base/creator';
import { Nation } from './nation';
import { NationNameTable } from '$lib/tables/locationTables/nationNameTable';
import { NationAdjectiveTable } from '$lib/tables/locationTables/nationAdjectiveTable';
import { TechnologyTable } from '$lib/tables/otherTables/technologyTable';
import { LandscapeTable } from '$lib/tables/locationTables/landscapeTable';
import { BasicResourceTable } from '$lib/tables/otherTables/basicResourceTable';
import { SizeTable } from '$lib/tables/otherTables/sizeTable';

export class NationCreator extends Creator<Nation> {
	/**
	 * Create RPG-mode nation (manual creation for RPG content)
	 * Sets isSimulationGenerated = false and uses simple narrative properties
	 */
	create(): Nation {
		const nation = new Nation();

		// Set mode flag
		nation.isSimulationGenerated = false;

		// Generate basic nation details
		nation.name = new NationNameTable().roleWithCascade(this.dice).text;
		nation.adjective = new NationAdjectiveTable().roleWithCascade(this.dice).text;

		// RPG-mode properties
		nation.technologyLevel = new TechnologyTable().roleWithCascade(this.dice).text;
		nation.landscape = new LandscapeTable().roleWithCascade(this.dice).text;
		nation.primaryResource = new BasicResourceTable().roleWithCascade(this.dice).text;
		nation.populationSize = new SizeTable().roleWithCascade(this.dice).text;
		nation.government = this.generateGovernment();

		// Generate description
		nation.description = this.generateDescription(nation);

		return nation;
	}

	/**
	 * Create simulation-mode nation (generated by SimulationEngine)
	 * Sets isSimulationGenerated = true and initializes all simulation mechanics
	 */
	static createFromSimulation(params: {
		name: string;
		adjective?: string;
		race?: string;
		foundingYear: number;
		leaderName: string;
		leaderTitle?: string;
		governmentType?: string;
		capitalCityId?: string;
		parentRegionalMapId: string;
		cultureTraits?: Partial<import('./nation').CultureTraits>;
	}): Nation {
		const nation = new Nation();

		// Set mode flag
		nation.isSimulationGenerated = true;

		// Basic properties
		nation.name = params.name;
		nation.adjective = params.adjective || `${params.name}ian`;
		nation.race = params.race || 'Human';
		nation.foundingYear = params.foundingYear;

		// Leadership
		nation.leaderName = params.leaderName;
		nation.leaderTitle = params.leaderTitle || 'Chief';
		nation.governmentType = params.governmentType || 'Tribal';

		// Territory
		nation.capitalCityId = params.capitalCityId;
		nation.parentRegionalMapId = params.parentRegionalMapId;

		// Culture traits
		if (params.cultureTraits) {
			nation.cultureTraits = { ...nation.cultureTraits, ...params.cultureTraits };
		}

		// Initialize with starting resources
		nation.resources.gold = 50;
		nation.yields.gold = 2;

		return nation;
	}

	private capitalize(text: string): string {
		if (!text) return '';
		return text.charAt(0).toUpperCase() + text.slice(1);
	}

	private generateGovernment(): string {
		const governments = [
			'monarchy',
			'republic',
			'theocracy',
			'oligarchy',
			'democracy',
			'dictatorship',
			'feudal system',
			'magocracy',
			'tribal council',
			'empire',
			'confederation',
			'anarchy'
		];
		const index = this.dice.rollInterval(0, governments.length - 1);
		return governments[index];
	}

	private generateDescription(nation: Nation): string {
		let desc = `${nation.name} is a${this.startsWithVowel(nation.adjective) ? 'n' : ''} ${nation.adjective} nation `;
		desc += `governed by a ${nation.government}. `;

		desc += `The land is characterized by ${nation.landscape}, `;
		desc += `and the population is ${nation.populationSize}. `;

		desc += `The nation's technology level is ${nation.technologyLevel}, `;
		desc += `and their primary resource is ${nation.primaryResource}.`;

		return desc;
	}

	private startsWithVowel(text: string): boolean {
		if (!text) return false;
		return /^[aeiou]/i.test(text);
	}
}
