import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class ActionsTable2 extends Table {
	constructor() {
		const entries = [
			new TableEntry('Advantage').withRoleInterval(1, 1),
			new TableEntry('Adversity').withRoleInterval(2, 2),
			new TableEntry('Agreement').withRoleInterval(3, 3),
			new TableEntry('Animal').withRoleInterval(4, 4),
			new TableEntry('Attention').withRoleInterval(5, 5),
			new TableEntry('Balance').withRoleInterval(6, 6),
			new TableEntry('Battle').withRoleInterval(7, 7),
			new TableEntry('Benefits').withRoleInterval(8, 8),
			new TableEntry('Building').withRoleInterval(9, 9),
			new TableEntry('Burden').withRoleInterval(10, 10),
			new TableEntry('Bureaucracy').withRoleInterval(11, 11),
			new TableEntry('Business').withRoleInterval(12, 12),
			new TableEntry('Chaos').withRoleInterval(13, 13),
			new TableEntry('Comfort').withRoleInterval(14, 14),
			new TableEntry('Completion').withRoleInterval(15, 15),
			new TableEntry('Conflict').withRoleInterval(16, 16),
			new TableEntry('Cooperation').withRoleInterval(17, 17),
			new TableEntry('Danger').withRoleInterval(18, 18),
			new TableEntry('Defense').withRoleInterval(19, 19),
			new TableEntry('Depletion').withRoleInterval(20, 20),
			new TableEntry('Disadvantage').withRoleInterval(21, 21),
			new TableEntry('Distraction').withRoleInterval(22, 22),
			new TableEntry('Elements').withRoleInterval(23, 23),
			new TableEntry('Emotion').withRoleInterval(24, 24),
			new TableEntry('Enemy').withRoleInterval(25, 25),
			new TableEntry('Energy').withRoleInterval(26, 26),
			new TableEntry('Environment').withRoleInterval(27, 27),
			new TableEntry('Expectation').withRoleInterval(28, 28),
			new TableEntry('Exterior').withRoleInterval(29, 29),
			new TableEntry('Extravagance').withRoleInterval(30, 30),
			new TableEntry('Failure').withRoleInterval(31, 31),
			new TableEntry('Fame').withRoleInterval(32, 32),
			new TableEntry('Fear').withRoleInterval(33, 33),
			new TableEntry('Freedom').withRoleInterval(34, 34),
			new TableEntry('Friend').withRoleInterval(35, 35),
			new TableEntry('Goal').withRoleInterval(36, 36),
			new TableEntry('Group').withRoleInterval(37, 37),
			new TableEntry('Health').withRoleInterval(38, 38),
			new TableEntry('Hindrance').withRoleInterval(39, 39),
			new TableEntry('Home').withRoleInterval(40, 40),
			new TableEntry('Hope').withRoleInterval(41, 41),
			new TableEntry('Idea').withRoleInterval(42, 42),
			new TableEntry('Illness').withRoleInterval(43, 43),
			new TableEntry('Illusion').withRoleInterval(44, 44),
			new TableEntry('Individual').withRoleInterval(45, 45),
			new TableEntry('Information').withRoleInterval(46, 46),
			new TableEntry('Innocent').withRoleInterval(47, 47),
			new TableEntry('Intellect').withRoleInterval(48, 48),
			new TableEntry('Interior').withRoleInterval(49, 49),
			new TableEntry('Investment').withRoleInterval(50, 50),
			new TableEntry('Leadership').withRoleInterval(51, 51),
			new TableEntry('Legal').withRoleInterval(52, 52),
			new TableEntry('Location').withRoleInterval(53, 53),
			new TableEntry('Military').withRoleInterval(54, 54),
			new TableEntry('Misfortune').withRoleInterval(55, 55),
			new TableEntry('Mundane').withRoleInterval(56, 56),
			new TableEntry('Nature').withRoleInterval(57, 57),
			new TableEntry('Needs').withRoleInterval(58, 58),
			new TableEntry('News').withRoleInterval(59, 59),
			new TableEntry('Normal').withRoleInterval(60, 60),
			new TableEntry('Object').withRoleInterval(61, 61),
			new TableEntry('Obscurity').withRoleInterval(62, 62),
			new TableEntry('Official').withRoleInterval(63, 63),
			new TableEntry('Opposition').withRoleInterval(64, 64),
			new TableEntry('Outside').withRoleInterval(65, 65),
			new TableEntry('Pain').withRoleInterval(66, 66),
			new TableEntry('Path').withRoleInterval(67, 67),
			new TableEntry('Peace').withRoleInterval(68, 68),
			new TableEntry('People').withRoleInterval(69, 69),
			new TableEntry('Personal').withRoleInterval(70, 70),
			new TableEntry('Physical').withRoleInterval(71, 71),
			new TableEntry('Plot').withRoleInterval(72, 72),
			new TableEntry('Portal').withRoleInterval(73, 73),
			new TableEntry('Possessions').withRoleInterval(74, 74),
			new TableEntry('Poverty').withRoleInterval(75, 75),
			new TableEntry('Power').withRoleInterval(76, 76),
			new TableEntry('Prison').withRoleInterval(77, 77),
			new TableEntry('Project').withRoleInterval(78, 78),
			new TableEntry('Protection').withRoleInterval(79, 79),
			new TableEntry('Reassurance').withRoleInterval(80, 80),
			new TableEntry('Representative').withRoleInterval(81, 81),
			new TableEntry('Riches').withRoleInterval(82, 82),
			new TableEntry('Safety').withRoleInterval(83, 83),
			new TableEntry('Strength').withRoleInterval(84, 84),
			new TableEntry('Success').withRoleInterval(85, 85),
			new TableEntry('Suffering').withRoleInterval(86, 86),
			new TableEntry('Surprise').withRoleInterval(87, 87),
			new TableEntry('Tactic').withRoleInterval(88, 88),
			new TableEntry('Technology').withRoleInterval(89, 89),
			new TableEntry('Tension').withRoleInterval(90, 90),
			new TableEntry('Time').withRoleInterval(91, 91),
			new TableEntry('Trial').withRoleInterval(92, 92),
			new TableEntry('Value').withRoleInterval(93, 93),
			new TableEntry('Vehicle').withRoleInterval(94, 94),
			new TableEntry('Victory').withRoleInterval(95, 95),
			new TableEntry('Vulnerability').withRoleInterval(96, 96),
			new TableEntry('Weapon').withRoleInterval(97, 97),
			new TableEntry('Weather').withRoleInterval(98, 98),
			new TableEntry('Work').withRoleInterval(99, 99),
			new TableEntry('Wound').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicActionsTable2, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
