import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

/**
 * Mythic GME Actions Table 1
 * Action words for creating narrative events
 */
export class ActionsTable1 extends Table {
	constructor() {
		const entries = [
			new TableEntry('Abandon').withRoleInterval(1, 1),
			new TableEntry('Accompany').withRoleInterval(2, 2),
			new TableEntry('Activate').withRoleInterval(3, 3),
			new TableEntry('Agree').withRoleInterval(4, 4),
			new TableEntry('Ambush').withRoleInterval(5, 5),
			new TableEntry('Arrive').withRoleInterval(6, 6),
			new TableEntry('Assist').withRoleInterval(7, 7),
			new TableEntry('Attack').withRoleInterval(8, 8),
			new TableEntry('Attain').withRoleInterval(9, 9),
			new TableEntry('Bargain').withRoleInterval(10, 10),
			new TableEntry('Befriend').withRoleInterval(11, 11),
			new TableEntry('Bestow').withRoleInterval(12, 12),
			new TableEntry('Betray').withRoleInterval(13, 13),
			new TableEntry('Block').withRoleInterval(14, 14),
			new TableEntry('Break').withRoleInterval(15, 15),
			new TableEntry('Carry').withRoleInterval(16, 16),
			new TableEntry('Celebrate').withRoleInterval(17, 17),
			new TableEntry('Change').withRoleInterval(18, 18),
			new TableEntry('Close').withRoleInterval(19, 19),
			new TableEntry('Combine').withRoleInterval(20, 20),
			new TableEntry('Communicate').withRoleInterval(21, 21),
			new TableEntry('Conceal').withRoleInterval(22, 22),
			new TableEntry('Continue').withRoleInterval(23, 23),
			new TableEntry('Control').withRoleInterval(24, 24),
			new TableEntry('Create').withRoleInterval(25, 25),
			new TableEntry('Deceive').withRoleInterval(26, 26),
			new TableEntry('Decrease').withRoleInterval(27, 27),
			new TableEntry('Defend').withRoleInterval(28, 28),
			new TableEntry('Delay').withRoleInterval(29, 29),
			new TableEntry('Deny').withRoleInterval(30, 30),
			new TableEntry('Depart').withRoleInterval(31, 31),
			new TableEntry('Deposit').withRoleInterval(32, 32),
			new TableEntry('Destroy').withRoleInterval(33, 33),
			new TableEntry('Dispute').withRoleInterval(34, 34),
			new TableEntry('Disrupt').withRoleInterval(35, 35),
			new TableEntry('Distrust').withRoleInterval(36, 36),
			new TableEntry('Divide').withRoleInterval(37, 37),
			new TableEntry('Drop').withRoleInterval(38, 38),
			new TableEntry('Easy').withRoleInterval(39, 39),
			new TableEntry('Energize').withRoleInterval(40, 40),
			new TableEntry('Escape').withRoleInterval(41, 41),
			new TableEntry('Expose').withRoleInterval(42, 42),
			new TableEntry('Fail').withRoleInterval(43, 43),
			new TableEntry('Fight').withRoleInterval(44, 44),
			new TableEntry('Flee').withRoleInterval(45, 45),
			new TableEntry('Free').withRoleInterval(46, 46),
			new TableEntry('Guide').withRoleInterval(47, 47),
			new TableEntry('Harm').withRoleInterval(48, 48),
			new TableEntry('Heal').withRoleInterval(49, 49),
			new TableEntry('Hinder').withRoleInterval(50, 50),
			new TableEntry('Imitate').withRoleInterval(51, 51),
			new TableEntry('Imprison').withRoleInterval(52, 52),
			new TableEntry('Increase').withRoleInterval(53, 53),
			new TableEntry('Indulge').withRoleInterval(54, 54),
			new TableEntry('Inform').withRoleInterval(55, 55),
			new TableEntry('Inquire').withRoleInterval(56, 56),
			new TableEntry('Inspect').withRoleInterval(57, 57),
			new TableEntry('Invade').withRoleInterval(58, 58),
			new TableEntry('Leave').withRoleInterval(59, 59),
			new TableEntry('Lure').withRoleInterval(60, 60),
			new TableEntry('Misuse').withRoleInterval(61, 61),
			new TableEntry('Move').withRoleInterval(62, 62),
			new TableEntry('Neglect').withRoleInterval(63, 63),
			new TableEntry('Observe').withRoleInterval(64, 64),
			new TableEntry('Open').withRoleInterval(65, 65),
			new TableEntry('Oppose').withRoleInterval(66, 66),
			new TableEntry('Overthrow').withRoleInterval(67, 67),
			new TableEntry('Praise').withRoleInterval(68, 68),
			new TableEntry('Proceed').withRoleInterval(69, 69),
			new TableEntry('Protect').withRoleInterval(70, 70),
			new TableEntry('Punish').withRoleInterval(71, 71),
			new TableEntry('Pursue').withRoleInterval(72, 72),
			new TableEntry('Recruit').withRoleInterval(73, 73),
			new TableEntry('Refuse').withRoleInterval(74, 74),
			new TableEntry('Release').withRoleInterval(75, 75),
			new TableEntry('Relinquish').withRoleInterval(76, 76),
			new TableEntry('Repair').withRoleInterval(77, 77),
			new TableEntry('Repulse').withRoleInterval(78, 78),
			new TableEntry('Return').withRoleInterval(79, 79),
			new TableEntry('Reward').withRoleInterval(80, 80),
			new TableEntry('Ruin').withRoleInterval(81, 81),
			new TableEntry('Separate').withRoleInterval(82, 82),
			new TableEntry('Start').withRoleInterval(83, 83),
			new TableEntry('Stop').withRoleInterval(84, 84),
			new TableEntry('Strange').withRoleInterval(85, 85),
			new TableEntry('Struggle').withRoleInterval(86, 86),
			new TableEntry('Succeed').withRoleInterval(87, 87),
			new TableEntry('Support').withRoleInterval(88, 88),
			new TableEntry('Suppress').withRoleInterval(89, 89),
			new TableEntry('Take').withRoleInterval(90, 90),
			new TableEntry('Threaten').withRoleInterval(91, 91),
			new TableEntry('Transform').withRoleInterval(92, 92),
			new TableEntry('Trap').withRoleInterval(93, 93),
			new TableEntry('Travel').withRoleInterval(94, 94),
			new TableEntry('Triumph').withRoleInterval(95, 95),
			new TableEntry('Truce').withRoleInterval(96, 96),
			new TableEntry('Trust').withRoleInterval(97, 97),
			new TableEntry('Use').withRoleInterval(98, 98),
			new TableEntry('Usurp').withRoleInterval(99, 99),
			new TableEntry('Waste').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicActionsTable1, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
