import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterActionsCombatTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Advances').withRoleInterval(1, 1),
			new TableEntry('Aims').withRoleInterval(2, 2),
			new TableEntry('Ambushes').withRoleInterval(3, 3),
			new TableEntry('Attacks').withRoleInterval(4, 4),
			new TableEntry('Baits').withRoleInterval(5, 5),
			new TableEntry('Bashes').withRoleInterval(6, 6),
			new TableEntry('Blocks').withRoleInterval(7, 7),
			new TableEntry('Charges').withRoleInterval(8, 8),
			new TableEntry('Chokes').withRoleInterval(9, 9),
			new TableEntry('Circles').withRoleInterval(10, 10),
			new TableEntry('Climbs').withRoleInterval(11, 11),
			new TableEntry('Counters').withRoleInterval(12, 12),
			new TableEntry('Covers').withRoleInterval(13, 13),
			new TableEntry('Crushes').withRoleInterval(14, 14),
			new TableEntry('Defends').withRoleInterval(15, 15),
			new TableEntry('Disarms').withRoleInterval(16, 16),
			new TableEntry('Dodges').withRoleInterval(17, 17),
			new TableEntry('Ducks').withRoleInterval(18, 18),
			new TableEntry('Duels').withRoleInterval(19, 19),
			new TableEntry('Encircles').withRoleInterval(20, 20),
			new TableEntry('Evades').withRoleInterval(21, 21),
			new TableEntry('Feints').withRoleInterval(22, 22),
			new TableEntry('Fights').withRoleInterval(23, 23),
			new TableEntry('Fires').withRoleInterval(24, 24),
			new TableEntry('Flanks').withRoleInterval(25, 25),
			new TableEntry('Flees').withRoleInterval(26, 26),
			new TableEntry('Grapples').withRoleInterval(27, 27),
			new TableEntry('Guards').withRoleInterval(28, 28),
			new TableEntry('Hides').withRoleInterval(29, 29),
			new TableEntry('Holds-Ground').withRoleInterval(30, 30),
			new TableEntry('Intimidates').withRoleInterval(31, 31),
			new TableEntry('Jabs').withRoleInterval(32, 32),
			new TableEntry('Jumps').withRoleInterval(33, 33),
			new TableEntry('Kicks').withRoleInterval(34, 34),
			new TableEntry('Leaps').withRoleInterval(35, 35),
			new TableEntry('Lunges').withRoleInterval(36, 36),
			new TableEntry('Maneuvers').withRoleInterval(37, 37),
			new TableEntry('Parries').withRoleInterval(38, 38),
			new TableEntry('Pounces').withRoleInterval(39, 39),
			new TableEntry('Prepares').withRoleInterval(40, 40),
			new TableEntry('Presses-Attack').withRoleInterval(41, 41),
			new TableEntry('Protects').withRoleInterval(42, 42),
			new TableEntry('Punches').withRoleInterval(43, 43),
			new TableEntry('Pursues').withRoleInterval(44, 44),
			new TableEntry('Pushes').withRoleInterval(45, 45),
			new TableEntry('Rallies').withRoleInterval(46, 46),
			new TableEntry('Readies').withRoleInterval(47, 47),
			new TableEntry('Reloads').withRoleInterval(48, 48),
			new TableEntry('Repositions').withRoleInterval(49, 49),
			new TableEntry('Retreats').withRoleInterval(50, 50),
			new TableEntry('Rolls').withRoleInterval(51, 51),
			new TableEntry('Rushes').withRoleInterval(52, 52),
			new TableEntry('Shields').withRoleInterval(53, 53),
			new TableEntry('Shoots').withRoleInterval(54, 54),
			new TableEntry('Sidesteps').withRoleInterval(55, 55),
			new TableEntry('Slashes').withRoleInterval(56, 56),
			new TableEntry('Spins').withRoleInterval(57, 57),
			new TableEntry('Stabs').withRoleInterval(58, 58),
			new TableEntry('Staggers').withRoleInterval(59, 59),
			new TableEntry('Stands-Firm').withRoleInterval(60, 60),
			new TableEntry('Strikes').withRoleInterval(61, 61),
			new TableEntry('Stumbles').withRoleInterval(62, 62),
			new TableEntry('Surprises').withRoleInterval(63, 63),
			new TableEntry('Surrenders').withRoleInterval(64, 64),
			new TableEntry('Swings').withRoleInterval(65, 65),
			new TableEntry('Tackles').withRoleInterval(66, 66),
			new TableEntry('Targets').withRoleInterval(67, 67),
			new TableEntry('Taunts').withRoleInterval(68, 68),
			new TableEntry('Threatens').withRoleInterval(69, 69),
			new TableEntry('Throws').withRoleInterval(70, 70),
			new TableEntry('Thrusts').withRoleInterval(71, 71),
			new TableEntry('Trips').withRoleInterval(72, 72),
			new TableEntry('Tumbles').withRoleInterval(73, 73),
			new TableEntry('Turns').withRoleInterval(74, 74),
			new TableEntry('Uses-Cover').withRoleInterval(75, 75),
			new TableEntry('Uses-Magic').withRoleInterval(76, 76),
			new TableEntry('Uses-Terrain').withRoleInterval(77, 77),
			new TableEntry('Waits').withRoleInterval(78, 78),
			new TableEntry('Wards').withRoleInterval(79, 79),
			new TableEntry('Watches').withRoleInterval(80, 80),
			new TableEntry('Weaves').withRoleInterval(81, 81),
			new TableEntry('Whirls').withRoleInterval(82, 82),
			new TableEntry('Wounds').withRoleInterval(83, 83),
			new TableEntry('Wrestles').withRoleInterval(84, 84),
			new TableEntry('Yields').withRoleInterval(85, 85),
			new TableEntry('Aims-Low').withRoleInterval(86, 86),
			new TableEntry('Aims-High').withRoleInterval(87, 87),
			new TableEntry('Goes-Berserk').withRoleInterval(88, 88),
			new TableEntry('Takes-Cover').withRoleInterval(89, 89),
			new TableEntry('Calls-For-Help').withRoleInterval(90, 90),
			new TableEntry('Disengages').withRoleInterval(91, 91),
			new TableEntry('Fights-Defensively').withRoleInterval(92, 92),
			new TableEntry('Fights-Recklessly').withRoleInterval(93, 93),
			new TableEntry('Uses-Ability').withRoleInterval(94, 94),
			new TableEntry('Uses-Item').withRoleInterval(95, 95),
			new TableEntry('Switches-Weapon').withRoleInterval(96, 96),
			new TableEntry('Adjusts-Strategy').withRoleInterval(97, 97),
			new TableEntry('Coordinates').withRoleInterval(98, 98),
			new TableEntry('Improvises').withRoleInterval(99, 99),
			new TableEntry('Hesitates').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterActionsCombat, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
