import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

/**
 * Mythic GME Characters Elements Table
 * Character descriptors for creating meaning
 */
export class CharactersElementsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Accompanied').withRoleInterval(1, 1),
			new TableEntry('Active').withRoleInterval(2, 2),
			new TableEntry('Aggressive').withRoleInterval(3, 3),
			new TableEntry('Ambush').withRoleInterval(4, 4),
			new TableEntry('Animal').withRoleInterval(5, 5),
			new TableEntry('Anxious').withRoleInterval(6, 6),
			new TableEntry('Armed').withRoleInterval(7, 7),
			new TableEntry('Beautiful').withRoleInterval(8, 8),
			new TableEntry('Bold').withRoleInterval(9, 9),
			new TableEntry('Busy').withRoleInterval(10, 10),
			new TableEntry('Calm').withRoleInterval(11, 11),
			new TableEntry('Careless').withRoleInterval(12, 12),
			new TableEntry('Casual').withRoleInterval(13, 13),
			new TableEntry('Cautious').withRoleInterval(14, 14),
			new TableEntry('Classy').withRoleInterval(15, 15),
			new TableEntry('Colorful').withRoleInterval(16, 16),
			new TableEntry('Combative').withRoleInterval(17, 17),
			new TableEntry('Crazy').withRoleInterval(18, 18),
			new TableEntry('Creepy').withRoleInterval(19, 19),
			new TableEntry('Curious').withRoleInterval(20, 20),
			new TableEntry('Dangerous').withRoleInterval(21, 21),
			new TableEntry('Deceitful').withRoleInterval(22, 22),
			new TableEntry('Defeated').withRoleInterval(23, 23),
			new TableEntry('Defiant').withRoleInterval(24, 24),
			new TableEntry('Delightful').withRoleInterval(25, 25),
			new TableEntry('Emotional').withRoleInterval(26, 26),
			new TableEntry('Energetic').withRoleInterval(27, 27),
			new TableEntry('Equipped').withRoleInterval(28, 28),
			new TableEntry('Excited').withRoleInterval(29, 29),
			new TableEntry('Expected').withRoleInterval(30, 30),
			new TableEntry('Familiar').withRoleInterval(31, 31),
			new TableEntry('Fast').withRoleInterval(32, 32),
			new TableEntry('Feeble').withRoleInterval(33, 33),
			new TableEntry('Feminine').withRoleInterval(34, 34),
			new TableEntry('Ferocious').withRoleInterval(35, 35),
			new TableEntry('Foe').withRoleInterval(36, 36),
			new TableEntry('Foolish').withRoleInterval(37, 37),
			new TableEntry('Fortunate').withRoleInterval(38, 38),
			new TableEntry('Fragrant').withRoleInterval(39, 39),
			new TableEntry('Frantic').withRoleInterval(40, 40),
			new TableEntry('Friend').withRoleInterval(41, 41),
			new TableEntry('Frightened').withRoleInterval(42, 42),
			new TableEntry('Frightening').withRoleInterval(43, 43),
			new TableEntry('Generous').withRoleInterval(44, 44),
			new TableEntry('Glad').withRoleInterval(45, 45),
			new TableEntry('Happy').withRoleInterval(46, 46),
			new TableEntry('Harmful').withRoleInterval(47, 47),
			new TableEntry('Helpful').withRoleInterval(48, 48),
			new TableEntry('Helpless').withRoleInterval(49, 49),
			new TableEntry('Hurt').withRoleInterval(50, 50),
			new TableEntry('Important').withRoleInterval(51, 51),
			new TableEntry('Inactive').withRoleInterval(52, 52),
			new TableEntry('Influential').withRoleInterval(53, 53),
			new TableEntry('Innocent').withRoleInterval(54, 54),
			new TableEntry('Intense').withRoleInterval(55, 55),
			new TableEntry('Knowledgeable').withRoleInterval(56, 56),
			new TableEntry('Large').withRoleInterval(57, 57),
			new TableEntry('Lonely').withRoleInterval(58, 58),
			new TableEntry('Loud').withRoleInterval(59, 59),
			new TableEntry('Loyal').withRoleInterval(60, 60),
			new TableEntry('Masculine').withRoleInterval(61, 61),
			new TableEntry('Mighty').withRoleInterval(62, 62),
			new TableEntry('Miserable').withRoleInterval(63, 63),
			new TableEntry('Multiple').withRoleInterval(64, 64),
			new TableEntry('Mundane').withRoleInterval(65, 65),
			new TableEntry('Mysterious').withRoleInterval(66, 66),
			new TableEntry('Natural').withRoleInterval(67, 67),
			new TableEntry('Odd').withRoleInterval(68, 68),
			new TableEntry('Official').withRoleInterval(69, 69),
			new TableEntry('Old').withRoleInterval(70, 70),
			new TableEntry('Passive').withRoleInterval(71, 71),
			new TableEntry('Peaceful').withRoleInterval(72, 72),
			new TableEntry('Playful').withRoleInterval(73, 73),
			new TableEntry('Powerful').withRoleInterval(74, 74),
			new TableEntry('Professional').withRoleInterval(75, 75),
			new TableEntry('Protected').withRoleInterval(76, 76),
			new TableEntry('Protecting').withRoleInterval(77, 77),
			new TableEntry('Questioning').withRoleInterval(78, 78),
			new TableEntry('Quiet').withRoleInterval(79, 79),
			new TableEntry('Reassuring').withRoleInterval(80, 80),
			new TableEntry('Resourceful').withRoleInterval(81, 81),
			new TableEntry('Seeking').withRoleInterval(82, 82),
			new TableEntry('Skilled').withRoleInterval(83, 83),
			new TableEntry('Slow').withRoleInterval(84, 84),
			new TableEntry('Small').withRoleInterval(85, 85),
			new TableEntry('Stealthy').withRoleInterval(86, 86),
			new TableEntry('Strange').withRoleInterval(87, 87),
			new TableEntry('Strong').withRoleInterval(88, 88),
			new TableEntry('Tall').withRoleInterval(89, 89),
			new TableEntry('Thieving').withRoleInterval(90, 90),
			new TableEntry('Threatening').withRoleInterval(91, 91),
			new TableEntry('Triumphant').withRoleInterval(92, 92),
			new TableEntry('Unexpected').withRoleInterval(93, 93),
			new TableEntry('Unnatural').withRoleInterval(94, 94),
			new TableEntry('Unusual').withRoleInterval(95, 95),
			new TableEntry('Violent').withRoleInterval(96, 96),
			new TableEntry('Vocal').withRoleInterval(97, 97),
			new TableEntry('Weak').withRoleInterval(98, 98),
			new TableEntry('Wild').withRoleInterval(99, 99),
			new TableEntry('Young').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharactersElements, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
