import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterActionsGeneralTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Abandons').withRoleInterval(1, 1),
			new TableEntry('Accepts').withRoleInterval(2, 2),
			new TableEntry('Acquires').withRoleInterval(3, 3),
			new TableEntry('Acts').withRoleInterval(4, 4),
			new TableEntry('Adapts').withRoleInterval(5, 5),
			new TableEntry('Agrees').withRoleInterval(6, 6),
			new TableEntry('Aids').withRoleInterval(7, 7),
			new TableEntry('Allows').withRoleInterval(8, 8),
			new TableEntry('Approaches').withRoleInterval(9, 9),
			new TableEntry('Argues').withRoleInterval(10, 10),
			new TableEntry('Arrives').withRoleInterval(11, 11),
			new TableEntry('Asks').withRoleInterval(12, 12),
			new TableEntry('Attempts').withRoleInterval(13, 13),
			new TableEntry('Avoids').withRoleInterval(14, 14),
			new TableEntry('Bargains').withRoleInterval(15, 15),
			new TableEntry('Begins').withRoleInterval(16, 16),
			new TableEntry('Betrays').withRoleInterval(17, 17),
			new TableEntry('Blames').withRoleInterval(18, 18),
			new TableEntry('Breaks').withRoleInterval(19, 19),
			new TableEntry('Brings').withRoleInterval(20, 20),
			new TableEntry('Builds').withRoleInterval(21, 21),
			new TableEntry('Calls').withRoleInterval(22, 22),
			new TableEntry('Carries').withRoleInterval(23, 23),
			new TableEntry('Celebrates').withRoleInterval(24, 24),
			new TableEntry('Changes').withRoleInterval(25, 25),
			new TableEntry('Chooses').withRoleInterval(26, 26),
			new TableEntry('Cleans').withRoleInterval(27, 27),
			new TableEntry('Climbs').withRoleInterval(28, 28),
			new TableEntry('Closes').withRoleInterval(29, 29),
			new TableEntry('Collaborates').withRoleInterval(30, 30),
			new TableEntry('Collects').withRoleInterval(31, 31),
			new TableEntry('Communicates').withRoleInterval(32, 32),
			new TableEntry('Completes').withRoleInterval(33, 33),
			new TableEntry('Conceals').withRoleInterval(34, 34),
			new TableEntry('Confronts').withRoleInterval(35, 35),
			new TableEntry('Connects').withRoleInterval(36, 36),
			new TableEntry('Considers').withRoleInterval(37, 37),
			new TableEntry('Constructs').withRoleInterval(38, 38),
			new TableEntry('Contacts').withRoleInterval(39, 39),
			new TableEntry('Contemplates').withRoleInterval(40, 40),
			new TableEntry('Continues').withRoleInterval(41, 41),
			new TableEntry('Cooperates').withRoleInterval(42, 42),
			new TableEntry('Creates').withRoleInterval(43, 43),
			new TableEntry('Crosses').withRoleInterval(44, 44),
			new TableEntry('Decides').withRoleInterval(45, 45),
			new TableEntry('Declines').withRoleInterval(46, 46),
			new TableEntry('Departs').withRoleInterval(47, 47),
			new TableEntry('Describes').withRoleInterval(48, 48),
			new TableEntry('Destroys').withRoleInterval(49, 49),
			new TableEntry('Discovers').withRoleInterval(50, 50),
			new TableEntry('Discusses').withRoleInterval(51, 51),
			new TableEntry('Disguises').withRoleInterval(52, 52),
			new TableEntry('Does-Nothing').withRoleInterval(53, 53),
			new TableEntry('Drinks').withRoleInterval(54, 54),
			new TableEntry('Drops').withRoleInterval(55, 55),
			new TableEntry('Eats').withRoleInterval(56, 56),
			new TableEntry('Encounters').withRoleInterval(57, 57),
			new TableEntry('Ends').withRoleInterval(58, 58),
			new TableEntry('Enters').withRoleInterval(59, 59),
			new TableEntry('Escapes').withRoleInterval(60, 60),
			new TableEntry('Examines').withRoleInterval(61, 61),
			new TableEntry('Explains').withRoleInterval(62, 62),
			new TableEntry('Explores').withRoleInterval(63, 63),
			new TableEntry('Fails').withRoleInterval(64, 64),
			new TableEntry('Finds').withRoleInterval(65, 65),
			new TableEntry('Finishes').withRoleInterval(66, 66),
			new TableEntry('Fixes').withRoleInterval(67, 67),
			new TableEntry('Flees').withRoleInterval(68, 68),
			new TableEntry('Follows').withRoleInterval(69, 69),
			new TableEntry('Forgets').withRoleInterval(70, 70),
			new TableEntry('Forgives').withRoleInterval(71, 71),
			new TableEntry('Gathers').withRoleInterval(72, 72),
			new TableEntry('Gives').withRoleInterval(73, 73),
			new TableEntry('Goes').withRoleInterval(74, 74),
			new TableEntry('Greets').withRoleInterval(75, 75),
			new TableEntry('Guides').withRoleInterval(76, 76),
			new TableEntry('Handles').withRoleInterval(77, 77),
			new TableEntry('Helps').withRoleInterval(78, 78),
			new TableEntry('Hides').withRoleInterval(79, 79),
			new TableEntry('Ignores').withRoleInterval(80, 80),
			new TableEntry('Improves').withRoleInterval(81, 81),
			new TableEntry('Informs').withRoleInterval(82, 82),
			new TableEntry('Initiates').withRoleInterval(83, 83),
			new TableEntry('Inspects').withRoleInterval(84, 84),
			new TableEntry('Interferes').withRoleInterval(85, 85),
			new TableEntry('Interrupts').withRoleInterval(86, 86),
			new TableEntry('Investigates').withRoleInterval(87, 87),
			new TableEntry('Joins').withRoleInterval(88, 88),
			new TableEntry('Journeys').withRoleInterval(89, 89),
			new TableEntry('Judges').withRoleInterval(90, 90),
			new TableEntry('Keeps').withRoleInterval(91, 91),
			new TableEntry('Knows').withRoleInterval(92, 92),
			new TableEntry('Laughs').withRoleInterval(93, 93),
			new TableEntry('Leads').withRoleInterval(94, 94),
			new TableEntry('Learns').withRoleInterval(95, 95),
			new TableEntry('Leaves').withRoleInterval(96, 96),
			new TableEntry('Listens').withRoleInterval(97, 97),
			new TableEntry('Looks').withRoleInterval(98, 98),
			new TableEntry('Loses').withRoleInterval(99, 99),
			new TableEntry('Makes').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterActionsGeneral, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
