import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

/**
 * Mythic GME Character Appearance Table
 * Physical description elements for characters
 */
export class CharacterAppearanceTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Aged').withRoleInterval(1, 1),
			new TableEntry('Athletic').withRoleInterval(2, 2),
			new TableEntry('Bald').withRoleInterval(3, 3),
			new TableEntry('Bearded').withRoleInterval(4, 4),
			new TableEntry('Beautiful').withRoleInterval(5, 5),
			new TableEntry('Bony').withRoleInterval(6, 6),
			new TableEntry('Brawny').withRoleInterval(7, 7),
			new TableEntry('Broad').withRoleInterval(8, 8),
			new TableEntry('Bushy-Eyebrowed').withRoleInterval(9, 9),
			new TableEntry('Chiseled').withRoleInterval(10, 10),
			new TableEntry('Clean-Shaven').withRoleInterval(11, 11),
			new TableEntry('Corpulent').withRoleInterval(12, 12),
			new TableEntry('Crooked').withRoleInterval(13, 13),
			new TableEntry('Curly-Haired').withRoleInterval(14, 14),
			new TableEntry('Dark-Eyed').withRoleInterval(15, 15),
			new TableEntry('Dark-Skinned').withRoleInterval(16, 16),
			new TableEntry('Disfigured').withRoleInterval(17, 17),
			new TableEntry('Elderly').withRoleInterval(18, 18),
			new TableEntry('Elegant').withRoleInterval(19, 19),
			new TableEntry('Fair-Skinned').withRoleInterval(20, 20),
			new TableEntry('Fit').withRoleInterval(21, 21),
			new TableEntry('Frail').withRoleInterval(22, 22),
			new TableEntry('Freckled').withRoleInterval(23, 23),
			new TableEntry('Gaunt').withRoleInterval(24, 24),
			new TableEntry('Graying').withRoleInterval(25, 25),
			new TableEntry('Handsome').withRoleInterval(26, 26),
			new TableEntry('Hairy').withRoleInterval(27, 27),
			new TableEntry('Heavy').withRoleInterval(28, 28),
			new TableEntry('Hunched').withRoleInterval(29, 29),
			new TableEntry('Lanky').withRoleInterval(30, 30),
			new TableEntry('Lean').withRoleInterval(31, 31),
			new TableEntry('Light-Eyed').withRoleInterval(32, 32),
			new TableEntry('Long-Faced').withRoleInterval(33, 33),
			new TableEntry('Long-Haired').withRoleInterval(34, 34),
			new TableEntry('Muscular').withRoleInterval(35, 35),
			new TableEntry('Narrow-Eyed').withRoleInterval(36, 36),
			new TableEntry('One-Eyed').withRoleInterval(37, 37),
			new TableEntry('Pale').withRoleInterval(38, 38),
			new TableEntry('Plain').withRoleInterval(39, 39),
			new TableEntry('Plump').withRoleInterval(40, 40),
			new TableEntry('Portly').withRoleInterval(41, 41),
			new TableEntry('Pretty').withRoleInterval(42, 42),
			new TableEntry('Refined').withRoleInterval(43, 43),
			new TableEntry('Rosy-Cheeked').withRoleInterval(44, 44),
			new TableEntry('Round-Faced').withRoleInterval(45, 45),
			new TableEntry('Rugged').withRoleInterval(46, 46),
			new TableEntry('Scarred').withRoleInterval(47, 47),
			new TableEntry('Sharp-Featured').withRoleInterval(48, 48),
			new TableEntry('Short').withRoleInterval(49, 49),
			new TableEntry('Short-Haired').withRoleInterval(50, 50),
			new TableEntry('Slender').withRoleInterval(51, 51),
			new TableEntry('Slight').withRoleInterval(52, 52),
			new TableEntry('Slim').withRoleInterval(53, 53),
			new TableEntry('Small').withRoleInterval(54, 54),
			new TableEntry('Smooth-Faced').withRoleInterval(55, 55),
			new TableEntry('Square-Jawed').withRoleInterval(56, 56),
			new TableEntry('Stocky').withRoleInterval(57, 57),
			new TableEntry('Stooped').withRoleInterval(58, 58),
			new TableEntry('Straight-Haired').withRoleInterval(59, 59),
			new TableEntry('Striking').withRoleInterval(60, 60),
			new TableEntry('Strong-Jawed').withRoleInterval(61, 61),
			new TableEntry('Sturdy').withRoleInterval(62, 62),
			new TableEntry('Sunburned').withRoleInterval(63, 63),
			new TableEntry('Tall').withRoleInterval(64, 64),
			new TableEntry('Tanned').withRoleInterval(65, 65),
			new TableEntry('Tattooed').withRoleInterval(66, 66),
			new TableEntry('Thick-Browed').withRoleInterval(67, 67),
			new TableEntry('Thin').withRoleInterval(68, 68),
			new TableEntry('Thin-Faced').withRoleInterval(69, 69),
			new TableEntry('Towering').withRoleInterval(70, 70),
			new TableEntry('Trim').withRoleInterval(71, 71),
			new TableEntry('Ugly').withRoleInterval(72, 72),
			new TableEntry('Unkempt').withRoleInterval(73, 73),
			new TableEntry('Weathered').withRoleInterval(74, 74),
			new TableEntry('Well-Built').withRoleInterval(75, 75),
			new TableEntry('Well-Dressed').withRoleInterval(76, 76),
			new TableEntry('Well-Groomed').withRoleInterval(77, 77),
			new TableEntry('Wide-Eyed').withRoleInterval(78, 78),
			new TableEntry('Wiry').withRoleInterval(79, 79),
			new TableEntry('Wrinkled').withRoleInterval(80, 80),
			new TableEntry('Young').withRoleInterval(81, 81),
			new TableEntry('Youthful').withRoleInterval(82, 82),
			new TableEntry('Pierced').withRoleInterval(83, 83),
			new TableEntry('Branded').withRoleInterval(84, 84),
			new TableEntry('Angular').withRoleInterval(85, 85),
			new TableEntry('Delicate').withRoleInterval(86, 86),
			new TableEntry('Graceful').withRoleInterval(87, 87),
			new TableEntry('Imposing').withRoleInterval(88, 88),
			new TableEntry('Intimidating').withRoleInterval(89, 89),
			new TableEntry('Majestic').withRoleInterval(90, 90),
			new TableEntry('Petite').withRoleInterval(91, 91),
			new TableEntry('Radiant').withRoleInterval(92, 92),
			new TableEntry('Robust').withRoleInterval(93, 93),
			new TableEntry('Regal').withRoleInterval(94, 94),
			new TableEntry('Scruffy').withRoleInterval(95, 95),
			new TableEntry('Shaggy').withRoleInterval(96, 96),
			new TableEntry('Sinewy').withRoleInterval(97, 97),
			new TableEntry('Willowy').withRoleInterval(98, 98),
			new TableEntry('Diminutive').withRoleInterval(99, 99),
			new TableEntry('Average').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterAppearance, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
