import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterDescriptorsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Abrasive').withRoleInterval(1, 1),
			new TableEntry('Accommodating').withRoleInterval(2, 2),
			new TableEntry('Active').withRoleInterval(3, 3),
			new TableEntry('Adventurous').withRoleInterval(4, 4),
			new TableEntry('Aggressive').withRoleInterval(5, 5),
			new TableEntry('Ambitious').withRoleInterval(6, 6),
			new TableEntry('Amusing').withRoleInterval(7, 7),
			new TableEntry('Angry').withRoleInterval(8, 8),
			new TableEntry('Anxious').withRoleInterval(9, 9),
			new TableEntry('Apathetic').withRoleInterval(10, 10),
			new TableEntry('Arrogant').withRoleInterval(11, 11),
			new TableEntry('Artistic').withRoleInterval(12, 12),
			new TableEntry('Assertive').withRoleInterval(13, 13),
			new TableEntry('Bold').withRoleInterval(14, 14),
			new TableEntry('Brave').withRoleInterval(15, 15),
			new TableEntry('Calculating').withRoleInterval(16, 16),
			new TableEntry('Calm').withRoleInterval(17, 17),
			new TableEntry('Capable').withRoleInterval(18, 18),
			new TableEntry('Careless').withRoleInterval(19, 19),
			new TableEntry('Caring').withRoleInterval(20, 20),
			new TableEntry('Cautious').withRoleInterval(21, 21),
			new TableEntry('Charming').withRoleInterval(22, 22),
			new TableEntry('Cheerful').withRoleInterval(23, 23),
			new TableEntry('Clever').withRoleInterval(24, 24),
			new TableEntry('Cold').withRoleInterval(25, 25),
			new TableEntry('Compassionate').withRoleInterval(26, 26),
			new TableEntry('Competent').withRoleInterval(27, 27),
			new TableEntry('Confident').withRoleInterval(28, 28),
			new TableEntry('Considerate').withRoleInterval(29, 29),
			new TableEntry('Controlled').withRoleInterval(30, 30),
			new TableEntry('Courageous').withRoleInterval(31, 31),
			new TableEntry('Cowardly').withRoleInterval(32, 32),
			new TableEntry('Crafty').withRoleInterval(33, 33),
			new TableEntry('Creative').withRoleInterval(34, 34),
			new TableEntry('Cruel').withRoleInterval(35, 35),
			new TableEntry('Cunning').withRoleInterval(36, 36),
			new TableEntry('Curious').withRoleInterval(37, 37),
			new TableEntry('Cynical').withRoleInterval(38, 38),
			new TableEntry('Dangerous').withRoleInterval(39, 39),
			new TableEntry('Daring').withRoleInterval(40, 40),
			new TableEntry('Deceitful').withRoleInterval(41, 41),
			new TableEntry('Decisive').withRoleInterval(42, 42),
			new TableEntry('Defensive').withRoleInterval(43, 43),
			new TableEntry('Defiant').withRoleInterval(44, 44),
			new TableEntry('Delicate').withRoleInterval(45, 45),
			new TableEntry('Dependable').withRoleInterval(46, 46),
			new TableEntry('Desperate').withRoleInterval(47, 47),
			new TableEntry('Determined').withRoleInterval(48, 48),
			new TableEntry('Devious').withRoleInterval(49, 49),
			new TableEntry('Dignified').withRoleInterval(50, 50),
			new TableEntry('Diplomatic').withRoleInterval(51, 51),
			new TableEntry('Dishonest').withRoleInterval(52, 52),
			new TableEntry('Distant').withRoleInterval(53, 53),
			new TableEntry('Distrustful').withRoleInterval(54, 54),
			new TableEntry('Driven').withRoleInterval(55, 55),
			new TableEntry('Eager').withRoleInterval(56, 56),
			new TableEntry('Eccentric').withRoleInterval(57, 57),
			new TableEntry('Efficient').withRoleInterval(58, 58),
			new TableEntry('Empathetic').withRoleInterval(59, 59),
			new TableEntry('Energetic').withRoleInterval(60, 60),
			new TableEntry('Enthusiastic').withRoleInterval(61, 61),
			new TableEntry('Experienced').withRoleInterval(62, 62),
			new TableEntry('Fearful').withRoleInterval(63, 63),
			new TableEntry('Fearless').withRoleInterval(64, 64),
			new TableEntry('Fierce').withRoleInterval(65, 65),
			new TableEntry('Foolish').withRoleInterval(66, 66),
			new TableEntry('Forgiving').withRoleInterval(67, 67),
			new TableEntry('Friendly').withRoleInterval(68, 68),
			new TableEntry('Generous').withRoleInterval(69, 69),
			new TableEntry('Gentle').withRoleInterval(70, 70),
			new TableEntry('Grim').withRoleInterval(71, 71),
			new TableEntry('Gruff').withRoleInterval(72, 72),
			new TableEntry('Hardened').withRoleInterval(73, 73),
			new TableEntry('Harsh').withRoleInterval(74, 74),
			new TableEntry('Haunted').withRoleInterval(75, 75),
			new TableEntry('Helpful').withRoleInterval(76, 76),
			new TableEntry('Hesitant').withRoleInterval(77, 77),
			new TableEntry('Honest').withRoleInterval(78, 78),
			new TableEntry('Honorable').withRoleInterval(79, 79),
			new TableEntry('Hopeful').withRoleInterval(80, 80),
			new TableEntry('Hostile').withRoleInterval(81, 81),
			new TableEntry('Humble').withRoleInterval(82, 82),
			new TableEntry('Humorous').withRoleInterval(83, 83),
			new TableEntry('Idealistic').withRoleInterval(84, 84),
			new TableEntry('Imaginative').withRoleInterval(85, 85),
			new TableEntry('Impatient').withRoleInterval(86, 86),
			new TableEntry('Impulsive').withRoleInterval(87, 87),
			new TableEntry('Independent').withRoleInterval(88, 88),
			new TableEntry('Indifferent').withRoleInterval(89, 89),
			new TableEntry('Inexperienced').withRoleInterval(90, 90),
			new TableEntry('Insecure').withRoleInterval(91, 91),
			new TableEntry('Insightful').withRoleInterval(92, 92),
			new TableEntry('Intelligent').withRoleInterval(93, 93),
			new TableEntry('Intense').withRoleInterval(94, 94),
			new TableEntry('Intimidating').withRoleInterval(95, 95),
			new TableEntry('Introverted').withRoleInterval(96, 96),
			new TableEntry('Jealous').withRoleInterval(97, 97),
			new TableEntry('Joyful').withRoleInterval(98, 98),
			new TableEntry('Kind').withRoleInterval(99, 99),
			new TableEntry('Lazy').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterDescriptors, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
