import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterIdentityTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Acolyte').withRoleInterval(1, 1),
			new TableEntry('Advisor').withRoleInterval(2, 2),
			new TableEntry('Ambassador').withRoleInterval(3, 3),
			new TableEntry('Apprentice').withRoleInterval(4, 4),
			new TableEntry('Aristocrat').withRoleInterval(5, 5),
			new TableEntry('Artisan').withRoleInterval(6, 6),
			new TableEntry('Artist').withRoleInterval(7, 7),
			new TableEntry('Assassin').withRoleInterval(8, 8),
			new TableEntry('Bandit').withRoleInterval(9, 9),
			new TableEntry('Barbarian').withRoleInterval(10, 10),
			new TableEntry('Bard').withRoleInterval(11, 11),
			new TableEntry('Beggar').withRoleInterval(12, 12),
			new TableEntry('Bodyguard').withRoleInterval(13, 13),
			new TableEntry('Bureaucrat').withRoleInterval(14, 14),
			new TableEntry('Captain').withRoleInterval(15, 15),
			new TableEntry('Champion').withRoleInterval(16, 16),
			new TableEntry('Child').withRoleInterval(17, 17),
			new TableEntry('Chosen-One').withRoleInterval(18, 18),
			new TableEntry('Citizen').withRoleInterval(19, 19),
			new TableEntry('Commander').withRoleInterval(20, 20),
			new TableEntry('Commoner').withRoleInterval(21, 21),
			new TableEntry('Conspirator').withRoleInterval(22, 22),
			new TableEntry('Courier').withRoleInterval(23, 23),
			new TableEntry('Courtier').withRoleInterval(24, 24),
			new TableEntry('Coward').withRoleInterval(25, 25),
			new TableEntry('Criminal').withRoleInterval(26, 26),
			new TableEntry('Cultist').withRoleInterval(27, 27),
			new TableEntry('Diplomat').withRoleInterval(28, 28),
			new TableEntry('Doctor').withRoleInterval(29, 29),
			new TableEntry('Elder').withRoleInterval(30, 30),
			new TableEntry('Enforcer').withRoleInterval(31, 31),
			new TableEntry('Engineer').withRoleInterval(32, 32),
			new TableEntry('Entertainer').withRoleInterval(33, 33),
			new TableEntry('Explorer').withRoleInterval(34, 34),
			new TableEntry('Farmer').withRoleInterval(35, 35),
			new TableEntry('Fighter').withRoleInterval(36, 36),
			new TableEntry('Follower').withRoleInterval(37, 37),
			new TableEntry('Fool').withRoleInterval(38, 38),
			new TableEntry('Fugitive').withRoleInterval(39, 39),
			new TableEntry('Gambler').withRoleInterval(40, 40),
			new TableEntry('General').withRoleInterval(41, 41),
			new TableEntry('Guard').withRoleInterval(42, 42),
			new TableEntry('Guide').withRoleInterval(43, 43),
			new TableEntry('Healer').withRoleInterval(44, 44),
			new TableEntry('Heir').withRoleInterval(45, 45),
			new TableEntry('Herald').withRoleInterval(46, 46),
			new TableEntry('Hero').withRoleInterval(47, 47),
			new TableEntry('Hunter').withRoleInterval(48, 48),
			new TableEntry('Inquisitor').withRoleInterval(49, 49),
			new TableEntry('Investigator').withRoleInterval(50, 50),
			new TableEntry('Judge').withRoleInterval(51, 51),
			new TableEntry('Knight').withRoleInterval(52, 52),
			new TableEntry('Laborer').withRoleInterval(53, 53),
			new TableEntry('Leader').withRoleInterval(54, 54),
			new TableEntry('Lord').withRoleInterval(55, 55),
			new TableEntry('Mage').withRoleInterval(56, 56),
			new TableEntry('Magistrate').withRoleInterval(57, 57),
			new TableEntry('Merchant').withRoleInterval(58, 58),
			new TableEntry('Mercenary').withRoleInterval(59, 59),
			new TableEntry('Messenger').withRoleInterval(60, 60),
			new TableEntry('Militia').withRoleInterval(61, 61),
			new TableEntry('Monk').withRoleInterval(62, 62),
			new TableEntry('Noble').withRoleInterval(63, 63),
			new TableEntry('Nomad').withRoleInterval(64, 64),
			new TableEntry('Officer').withRoleInterval(65, 65),
			new TableEntry('Oracle').withRoleInterval(66, 66),
			new TableEntry('Outcast').withRoleInterval(67, 67),
			new TableEntry('Outlaw').withRoleInterval(68, 68),
			new TableEntry('Overseer').withRoleInterval(69, 69),
			new TableEntry('Peasant').withRoleInterval(70, 70),
			new TableEntry('Performer').withRoleInterval(71, 71),
			new TableEntry('Pilgrim').withRoleInterval(72, 72),
			new TableEntry('Pirate').withRoleInterval(73, 73),
			new TableEntry('Politician').withRoleInterval(74, 74),
			new TableEntry('Priest').withRoleInterval(75, 75),
			new TableEntry('Prince').withRoleInterval(76, 76),
			new TableEntry('Princess').withRoleInterval(77, 77),
			new TableEntry('Prisoner').withRoleInterval(78, 78),
			new TableEntry('Prophet').withRoleInterval(79, 79),
			new TableEntry('Ranger').withRoleInterval(80, 80),
			new TableEntry('Rebel').withRoleInterval(81, 81),
			new TableEntry('Refugee').withRoleInterval(82, 82),
			new TableEntry('Rogue').withRoleInterval(83, 83),
			new TableEntry('Ruler').withRoleInterval(84, 84),
			new TableEntry('Sage').withRoleInterval(85, 85),
			new TableEntry('Sailor').withRoleInterval(86, 86),
			new TableEntry('Scholar').withRoleInterval(87, 87),
			new TableEntry('Scout').withRoleInterval(88, 88),
			new TableEntry('Servant').withRoleInterval(89, 89),
			new TableEntry('Shaman').withRoleInterval(90, 90),
			new TableEntry('Slave').withRoleInterval(91, 91),
			new TableEntry('Smuggler').withRoleInterval(92, 92),
			new TableEntry('Soldier').withRoleInterval(93, 93),
			new TableEntry('Spy').withRoleInterval(94, 94),
			new TableEntry('Thief').withRoleInterval(95, 95),
			new TableEntry('Trader').withRoleInterval(96, 96),
			new TableEntry('Traveler').withRoleInterval(97, 97),
			new TableEntry('Veteran').withRoleInterval(98, 98),
			new TableEntry('Villager').withRoleInterval(99, 99),
			new TableEntry('Warrior').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterIdentity, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
