import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterPersonalityTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Adaptable').withRoleInterval(1, 1),
			new TableEntry('Adventurous').withRoleInterval(2, 2),
			new TableEntry('Affable').withRoleInterval(3, 3),
			new TableEntry('Aloof').withRoleInterval(4, 4),
			new TableEntry('Ambitious').withRoleInterval(5, 5),
			new TableEntry('Analytical').withRoleInterval(6, 6),
			new TableEntry('Anxious').withRoleInterval(7, 7),
			new TableEntry('Arrogant').withRoleInterval(8, 8),
			new TableEntry('Artistic').withRoleInterval(9, 9),
			new TableEntry('Assertive').withRoleInterval(10, 10),
			new TableEntry('Bitter').withRoleInterval(11, 11),
			new TableEntry('Bold').withRoleInterval(12, 12),
			new TableEntry('Bossy').withRoleInterval(13, 13),
			new TableEntry('Brash').withRoleInterval(14, 14),
			new TableEntry('Brave').withRoleInterval(15, 15),
			new TableEntry('Brooding').withRoleInterval(16, 16),
			new TableEntry('Callous').withRoleInterval(17, 17),
			new TableEntry('Calm').withRoleInterval(18, 18),
			new TableEntry('Carefree').withRoleInterval(19, 19),
			new TableEntry('Cautious').withRoleInterval(20, 20),
			new TableEntry('Charismatic').withRoleInterval(21, 21),
			new TableEntry('Cheerful').withRoleInterval(22, 22),
			new TableEntry('Cold').withRoleInterval(23, 23),
			new TableEntry('Compassionate').withRoleInterval(24, 24),
			new TableEntry('Competitive').withRoleInterval(25, 25),
			new TableEntry('Confident').withRoleInterval(26, 26),
			new TableEntry('Conservative').withRoleInterval(27, 27),
			new TableEntry('Contemplative').withRoleInterval(28, 28),
			new TableEntry('Controlling').withRoleInterval(29, 29),
			new TableEntry('Courageous').withRoleInterval(30, 30),
			new TableEntry('Cowardly').withRoleInterval(31, 31),
			new TableEntry('Creative').withRoleInterval(32, 32),
			new TableEntry('Critical').withRoleInterval(33, 33),
			new TableEntry('Cruel').withRoleInterval(34, 34),
			new TableEntry('Cunning').withRoleInterval(35, 35),
			new TableEntry('Curious').withRoleInterval(36, 36),
			new TableEntry('Cynical').withRoleInterval(37, 37),
			new TableEntry('Daring').withRoleInterval(38, 38),
			new TableEntry('Decisive').withRoleInterval(39, 39),
			new TableEntry('Defensive').withRoleInterval(40, 40),
			new TableEntry('Defiant').withRoleInterval(41, 41),
			new TableEntry('Dependable').withRoleInterval(42, 42),
			new TableEntry('Depressed').withRoleInterval(43, 43),
			new TableEntry('Detached').withRoleInterval(44, 44),
			new TableEntry('Determined').withRoleInterval(45, 45),
			new TableEntry('Diplomatic').withRoleInterval(46, 46),
			new TableEntry('Disciplined').withRoleInterval(47, 47),
			new TableEntry('Dishonest').withRoleInterval(48, 48),
			new TableEntry('Distrustful').withRoleInterval(49, 49),
			new TableEntry('Dramatic').withRoleInterval(50, 50),
			new TableEntry('Driven').withRoleInterval(51, 51),
			new TableEntry('Eccentric').withRoleInterval(52, 52),
			new TableEntry('Efficient').withRoleInterval(53, 53),
			new TableEntry('Easygoing').withRoleInterval(54, 54),
			new TableEntry('Empathetic').withRoleInterval(55, 55),
			new TableEntry('Energetic').withRoleInterval(56, 56),
			new TableEntry('Enthusiastic').withRoleInterval(57, 57),
			new TableEntry('Fearful').withRoleInterval(58, 58),
			new TableEntry('Fierce').withRoleInterval(59, 59),
			new TableEntry('Flamboyant').withRoleInterval(60, 60),
			new TableEntry('Focused').withRoleInterval(61, 61),
			new TableEntry('Foolish').withRoleInterval(62, 62),
			new TableEntry('Forgiving').withRoleInterval(63, 63),
			new TableEntry('Friendly').withRoleInterval(64, 64),
			new TableEntry('Generous').withRoleInterval(65, 65),
			new TableEntry('Gentle').withRoleInterval(66, 66),
			new TableEntry('Gloomy').withRoleInterval(67, 67),
			new TableEntry('Gracious').withRoleInterval(68, 68),
			new TableEntry('Grim').withRoleInterval(69, 69),
			new TableEntry('Gruff').withRoleInterval(70, 70),
			new TableEntry('Guarded').withRoleInterval(71, 71),
			new TableEntry('Gullible').withRoleInterval(72, 72),
			new TableEntry('Happy').withRoleInterval(73, 73),
			new TableEntry('Harsh').withRoleInterval(74, 74),
			new TableEntry('Headstrong').withRoleInterval(75, 75),
			new TableEntry('Helpful').withRoleInterval(76, 76),
			new TableEntry('Honest').withRoleInterval(77, 77),
			new TableEntry('Honorable').withRoleInterval(78, 78),
			new TableEntry('Hopeful').withRoleInterval(79, 79),
			new TableEntry('Hostile').withRoleInterval(80, 80),
			new TableEntry('Humble').withRoleInterval(81, 81),
			new TableEntry('Humorous').withRoleInterval(82, 82),
			new TableEntry('Idealistic').withRoleInterval(83, 83),
			new TableEntry('Imaginative').withRoleInterval(84, 84),
			new TableEntry('Impatient').withRoleInterval(85, 85),
			new TableEntry('Impulsive').withRoleInterval(86, 86),
			new TableEntry('Independent').withRoleInterval(87, 87),
			new TableEntry('Indifferent').withRoleInterval(88, 88),
			new TableEntry('Insecure').withRoleInterval(89, 89),
			new TableEntry('Intelligent').withRoleInterval(90, 90),
			new TableEntry('Intense').withRoleInterval(91, 91),
			new TableEntry('Introverted').withRoleInterval(92, 92),
			new TableEntry('Jealous').withRoleInterval(93, 93),
			new TableEntry('Joyful').withRoleInterval(94, 94),
			new TableEntry('Kind').withRoleInterval(95, 95),
			new TableEntry('Lazy').withRoleInterval(96, 96),
			new TableEntry('Logical').withRoleInterval(97, 97),
			new TableEntry('Loyal').withRoleInterval(98, 98),
			new TableEntry('Manipulative').withRoleInterval(99, 99),
			new TableEntry('Mature').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterPersonality, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
