import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterBackgroundTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Abandoned').withRoleInterval(1, 1),
			new TableEntry('Accomplished').withRoleInterval(2, 2),
			new TableEntry('Adopted').withRoleInterval(3, 3),
			new TableEntry('Apprenticed').withRoleInterval(4, 4),
			new TableEntry('Banished').withRoleInterval(5, 5),
			new TableEntry('Blessed').withRoleInterval(6, 6),
			new TableEntry('Burdened').withRoleInterval(7, 7),
			new TableEntry('Captured').withRoleInterval(8, 8),
			new TableEntry('Celebrated').withRoleInterval(9, 9),
			new TableEntry('Chosen').withRoleInterval(10, 10),
			new TableEntry('Common-Born').withRoleInterval(11, 11),
			new TableEntry('Conquered').withRoleInterval(12, 12),
			new TableEntry('Cursed').withRoleInterval(13, 13),
			new TableEntry('Dangerous').withRoleInterval(14, 14),
			new TableEntry('Defeated').withRoleInterval(15, 15),
			new TableEntry('Destitute').withRoleInterval(16, 16),
			new TableEntry('Disgraced').withRoleInterval(17, 17),
			new TableEntry('Educated').withRoleInterval(18, 18),
			new TableEntry('Elevated').withRoleInterval(19, 19),
			new TableEntry('Enslaved').withRoleInterval(20, 20),
			new TableEntry('Escaped').withRoleInterval(21, 21),
			new TableEntry('Exiled').withRoleInterval(22, 22),
			new TableEntry('Famous').withRoleInterval(23, 23),
			new TableEntry('Forgotten').withRoleInterval(24, 24),
			new TableEntry('Fortunate').withRoleInterval(25, 25),
			new TableEntry('Foundling').withRoleInterval(26, 26),
			new TableEntry('Free').withRoleInterval(27, 27),
			new TableEntry('Gifted').withRoleInterval(28, 28),
			new TableEntry('Hardened').withRoleInterval(29, 29),
			new TableEntry('Haunted').withRoleInterval(30, 30),
			new TableEntry('Heir').withRoleInterval(31, 31),
			new TableEntry('Hidden').withRoleInterval(32, 32),
			new TableEntry('Honored').withRoleInterval(33, 33),
			new TableEntry('Humble').withRoleInterval(34, 34),
			new TableEntry('Hunted').withRoleInterval(35, 35),
			new TableEntry('Illegitimate').withRoleInterval(36, 36),
			new TableEntry('Imprisoned').withRoleInterval(37, 37),
			new TableEntry('Indebted').withRoleInterval(38, 38),
			new TableEntry('Influential').withRoleInterval(39, 39),
			new TableEntry('Initiated').withRoleInterval(40, 40),
			new TableEntry('Inspired').withRoleInterval(41, 41),
			new TableEntry('Lost').withRoleInterval(42, 42),
			new TableEntry('Lowborn').withRoleInterval(43, 43),
			new TableEntry('Military').withRoleInterval(44, 44),
			new TableEntry('Mysterious').withRoleInterval(45, 45),
			new TableEntry('Noble').withRoleInterval(46, 46),
			new TableEntry('Nomadic').withRoleInterval(47, 47),
			new TableEntry('Orphaned').withRoleInterval(48, 48),
			new TableEntry('Outcast').withRoleInterval(49, 49),
			new TableEntry('Peasant').withRoleInterval(50, 50),
			new TableEntry('Persecuted').withRoleInterval(51, 51),
			new TableEntry('Privileged').withRoleInterval(52, 52),
			new TableEntry('Prophesied').withRoleInterval(53, 53),
			new TableEntry('Protected').withRoleInterval(54, 54),
			new TableEntry('Raised-By-Animals').withRoleInterval(55, 55),
			new TableEntry('Rebel').withRoleInterval(56, 56),
			new TableEntry('Redeemed').withRoleInterval(57, 57),
			new TableEntry('Reformed').withRoleInterval(58, 58),
			new TableEntry('Religious').withRoleInterval(59, 59),
			new TableEntry('Renowned').withRoleInterval(60, 60),
			new TableEntry('Rescued').withRoleInterval(61, 61),
			new TableEntry('Revered').withRoleInterval(62, 62),
			new TableEntry('Rich').withRoleInterval(63, 63),
			new TableEntry('Royal').withRoleInterval(64, 64),
			new TableEntry('Rural').withRoleInterval(65, 65),
			new TableEntry('Savage').withRoleInterval(66, 66),
			new TableEntry('Scholarly').withRoleInterval(67, 67),
			new TableEntry('Secretive').withRoleInterval(68, 68),
			new TableEntry('Self-Made').withRoleInterval(69, 69),
			new TableEntry('Sheltered').withRoleInterval(70, 70),
			new TableEntry('Skilled').withRoleInterval(71, 71),
			new TableEntry('Sold').withRoleInterval(72, 72),
			new TableEntry('Stolen').withRoleInterval(73, 73),
			new TableEntry('Street').withRoleInterval(74, 74),
			new TableEntry('Struggling').withRoleInterval(75, 75),
			new TableEntry('Survivor').withRoleInterval(76, 76),
			new TableEntry('Tested').withRoleInterval(77, 77),
			new TableEntry('Titled').withRoleInterval(78, 78),
			new TableEntry('Tough').withRoleInterval(79, 79),
			new TableEntry('Tragic').withRoleInterval(80, 80),
			new TableEntry('Trained').withRoleInterval(81, 81),
			new TableEntry('Traumatized').withRoleInterval(82, 82),
			new TableEntry('Traveled').withRoleInterval(83, 83),
			new TableEntry('Tribal').withRoleInterval(84, 84),
			new TableEntry('Troubled').withRoleInterval(85, 85),
			new TableEntry('Unique').withRoleInterval(86, 86),
			new TableEntry('Unknown').withRoleInterval(87, 87),
			new TableEntry('Unproven').withRoleInterval(88, 88),
			new TableEntry('Urban').withRoleInterval(89, 89),
			new TableEntry('Vengeful').withRoleInterval(90, 90),
			new TableEntry('Victorious').withRoleInterval(91, 91),
			new TableEntry('Wanted').withRoleInterval(92, 92),
			new TableEntry('Wealthy').withRoleInterval(93, 93),
			new TableEntry('Well-Connected').withRoleInterval(94, 94),
			new TableEntry('Wilderness').withRoleInterval(95, 95),
			new TableEntry('Wise').withRoleInterval(96, 96),
			new TableEntry('Witnessed').withRoleInterval(97, 97),
			new TableEntry('Working-Class').withRoleInterval(98, 98),
			new TableEntry('Worldly').withRoleInterval(99, 99),
			new TableEntry('Wronged').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterBackground, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
