import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterTraitsFlawsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Abrasive').withRoleInterval(1, 1),
			new TableEntry('Absent-Minded').withRoleInterval(2, 2),
			new TableEntry('Addiction').withRoleInterval(3, 3),
			new TableEntry('Aggressive').withRoleInterval(4, 4),
			new TableEntry('Ambitious').withRoleInterval(5, 5),
			new TableEntry('Anxiety').withRoleInterval(6, 6),
			new TableEntry('Arrogance').withRoleInterval(7, 7),
			new TableEntry('Avarice').withRoleInterval(8, 8),
			new TableEntry('Bitterness').withRoleInterval(9, 9),
			new TableEntry('Bloodthirsty').withRoleInterval(10, 10),
			new TableEntry('Boastful').withRoleInterval(11, 11),
			new TableEntry('Brash').withRoleInterval(12, 12),
			new TableEntry('Callousness').withRoleInterval(13, 13),
			new TableEntry('Careless').withRoleInterval(14, 14),
			new TableEntry('Clumsy').withRoleInterval(15, 15),
			new TableEntry('Cowardice').withRoleInterval(16, 16),
			new TableEntry('Cruelty').withRoleInterval(17, 17),
			new TableEntry('Cynicism').withRoleInterval(18, 18),
			new TableEntry('Deceitful').withRoleInterval(19, 19),
			new TableEntry('Defiant').withRoleInterval(20, 20),
			new TableEntry('Delusion').withRoleInterval(21, 21),
			new TableEntry('Dependence').withRoleInterval(22, 22),
			new TableEntry('Dishonest').withRoleInterval(23, 23),
			new TableEntry('Distrustful').withRoleInterval(24, 24),
			new TableEntry('Envious').withRoleInterval(25, 25),
			new TableEntry('Fanaticism').withRoleInterval(26, 26),
			new TableEntry('Fearful').withRoleInterval(27, 27),
			new TableEntry('Foolhardy').withRoleInterval(28, 28),
			new TableEntry('Forgetful').withRoleInterval(29, 29),
			new TableEntry('Gluttonous').withRoleInterval(30, 30),
			new TableEntry('Gossip').withRoleInterval(31, 31),
			new TableEntry('Greedy').withRoleInterval(32, 32),
			new TableEntry('Gullible').withRoleInterval(33, 33),
			new TableEntry('Haunted').withRoleInterval(34, 34),
			new TableEntry('Hedonistic').withRoleInterval(35, 35),
			new TableEntry('Hotheaded').withRoleInterval(36, 36),
			new TableEntry('Ignorant').withRoleInterval(37, 37),
			new TableEntry('Impatient').withRoleInterval(38, 38),
			new TableEntry('Impulsive').withRoleInterval(39, 39),
			new TableEntry('Indecisive').withRoleInterval(40, 40),
			new TableEntry('Insecure').withRoleInterval(41, 41),
			new TableEntry('Intolerant').withRoleInterval(42, 42),
			new TableEntry('Jealous').withRoleInterval(43, 43),
			new TableEntry('Judgmental').withRoleInterval(44, 44),
			new TableEntry('Lazy').withRoleInterval(45, 45),
			new TableEntry('Lecherous').withRoleInterval(46, 46),
			new TableEntry('Liar').withRoleInterval(47, 47),
			new TableEntry('Lustful').withRoleInterval(48, 48),
			new TableEntry('Manipulative').withRoleInterval(49, 49),
			new TableEntry('Martyr-Complex').withRoleInterval(50, 50),
			new TableEntry('Melodramatic').withRoleInterval(51, 51),
			new TableEntry('Merciless').withRoleInterval(52, 52),
			new TableEntry('Moody').withRoleInterval(53, 53),
			new TableEntry('Naive').withRoleInterval(54, 54),
			new TableEntry('Narcissistic').withRoleInterval(55, 55),
			new TableEntry('Obsessive').withRoleInterval(56, 56),
			new TableEntry('Opinionated').withRoleInterval(57, 57),
			new TableEntry('Overconfident').withRoleInterval(58, 58),
			new TableEntry('Overprotective').withRoleInterval(59, 59),
			new TableEntry('Paranoid').withRoleInterval(60, 60),
			new TableEntry('Perfectionist').withRoleInterval(61, 61),
			new TableEntry('Pessimistic').withRoleInterval(62, 62),
			new TableEntry('Phobia').withRoleInterval(63, 63),
			new TableEntry('Pompous').withRoleInterval(64, 64),
			new TableEntry('Possessive').withRoleInterval(65, 65),
			new TableEntry('Prejudiced').withRoleInterval(66, 66),
			new TableEntry('Prideful').withRoleInterval(67, 67),
			new TableEntry('Quick-Tempered').withRoleInterval(68, 68),
			new TableEntry('Rash').withRoleInterval(69, 69),
			new TableEntry('Reckless').withRoleInterval(70, 70),
			new TableEntry('Resentful').withRoleInterval(71, 71),
			new TableEntry('Ruthless').withRoleInterval(72, 72),
			new TableEntry('Sadistic').withRoleInterval(73, 73),
			new TableEntry('Sarcastic').withRoleInterval(74, 74),
			new TableEntry('Secretive').withRoleInterval(75, 75),
			new TableEntry('Self-Centered').withRoleInterval(76, 76),
			new TableEntry('Self-Destructive').withRoleInterval(77, 77),
			new TableEntry('Selfish').withRoleInterval(78, 78),
			new TableEntry('Shrewd').withRoleInterval(79, 79),
			new TableEntry('Shy').withRoleInterval(80, 80),
			new TableEntry('Slothful').withRoleInterval(81, 81),
			new TableEntry('Spiteful').withRoleInterval(82, 82),
			new TableEntry('Spoiled').withRoleInterval(83, 83),
			new TableEntry('Stubborn').withRoleInterval(84, 84),
			new TableEntry('Superstitious').withRoleInterval(85, 85),
			new TableEntry('Suspicious').withRoleInterval(86, 86),
			new TableEntry('Tactless').withRoleInterval(87, 87),
			new TableEntry('Temperamental').withRoleInterval(88, 88),
			new TableEntry('Timid').withRoleInterval(89, 89),
			new TableEntry('Treacherous').withRoleInterval(90, 90),
			new TableEntry('Trusting').withRoleInterval(91, 91),
			new TableEntry('Tyrannical').withRoleInterval(92, 92),
			new TableEntry('Unforgiving').withRoleInterval(93, 93),
			new TableEntry('Unreliable').withRoleInterval(94, 94),
			new TableEntry('Vain').withRoleInterval(95, 95),
			new TableEntry('Vengeful').withRoleInterval(96, 96),
			new TableEntry('Violent').withRoleInterval(97, 97),
			new TableEntry('Volatile').withRoleInterval(98, 98),
			new TableEntry('Weak-Willed').withRoleInterval(99, 99),
			new TableEntry('Wrathful').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterTraitsFlaws, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
