import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterSkillsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Acrobatics').withRoleInterval(1, 1),
			new TableEntry('Acting').withRoleInterval(2, 2),
			new TableEntry('Alchemy').withRoleInterval(3, 3),
			new TableEntry('Animal-Handling').withRoleInterval(4, 4),
			new TableEntry('Archery').withRoleInterval(5, 5),
			new TableEntry('Architecture').withRoleInterval(6, 6),
			new TableEntry('Armorcrafting').withRoleInterval(7, 7),
			new TableEntry('Artistry').withRoleInterval(8, 8),
			new TableEntry('Athletics').withRoleInterval(9, 9),
			new TableEntry('Bargaining').withRoleInterval(10, 10),
			new TableEntry('Blacksmithing').withRoleInterval(11, 11),
			new TableEntry('Bluffing').withRoleInterval(12, 12),
			new TableEntry('Brewing').withRoleInterval(13, 13),
			new TableEntry('Carpentry').withRoleInterval(14, 14),
			new TableEntry('Cartography').withRoleInterval(15, 15),
			new TableEntry('Climbing').withRoleInterval(16, 16),
			new TableEntry('Combat').withRoleInterval(17, 17),
			new TableEntry('Cooking').withRoleInterval(18, 18),
			new TableEntry('Crafting').withRoleInterval(19, 19),
			new TableEntry('Dancing').withRoleInterval(20, 20),
			new TableEntry('Deception').withRoleInterval(21, 21),
			new TableEntry('Diplomacy').withRoleInterval(22, 22),
			new TableEntry('Disguise').withRoleInterval(23, 23),
			new TableEntry('Divination').withRoleInterval(24, 24),
			new TableEntry('Engineering').withRoleInterval(25, 25),
			new TableEntry('Escapology').withRoleInterval(26, 26),
			new TableEntry('Etiquette').withRoleInterval(27, 27),
			new TableEntry('Falconry').withRoleInterval(28, 28),
			new TableEntry('Farming').withRoleInterval(29, 29),
			new TableEntry('First-Aid').withRoleInterval(30, 30),
			new TableEntry('Fishing').withRoleInterval(31, 31),
			new TableEntry('Forgery').withRoleInterval(32, 32),
			new TableEntry('Fortune-Telling').withRoleInterval(33, 33),
			new TableEntry('Gambling').withRoleInterval(34, 34),
			new TableEntry('Geography').withRoleInterval(35, 35),
			new TableEntry('Healing').withRoleInterval(36, 36),
			new TableEntry('Herbalism').withRoleInterval(37, 37),
			new TableEntry('History').withRoleInterval(38, 38),
			new TableEntry('Horsemanship').withRoleInterval(39, 39),
			new TableEntry('Hunting').withRoleInterval(40, 40),
			new TableEntry('Illusion').withRoleInterval(41, 41),
			new TableEntry('Improvisation').withRoleInterval(42, 42),
			new TableEntry('Insight').withRoleInterval(43, 43),
			new TableEntry('Intimidation').withRoleInterval(44, 44),
			new TableEntry('Investigation').withRoleInterval(45, 45),
			new TableEntry('Jewelry-Making').withRoleInterval(46, 46),
			new TableEntry('Juggling').withRoleInterval(47, 47),
			new TableEntry('Law').withRoleInterval(48, 48),
			new TableEntry('Leadership').withRoleInterval(49, 49),
			new TableEntry('Leatherworking').withRoleInterval(50, 50),
			new TableEntry('Linguistics').withRoleInterval(51, 51),
			new TableEntry('Literacy').withRoleInterval(52, 52),
			new TableEntry('Lockpicking').withRoleInterval(53, 53),
			new TableEntry('Lore').withRoleInterval(54, 54),
			new TableEntry('Magic').withRoleInterval(55, 55),
			new TableEntry('Mathematics').withRoleInterval(56, 56),
			new TableEntry('Medicine').withRoleInterval(57, 57),
			new TableEntry('Meditation').withRoleInterval(58, 58),
			new TableEntry('Mining').withRoleInterval(59, 59),
			new TableEntry('Music').withRoleInterval(60, 60),
			new TableEntry('Navigation').withRoleInterval(61, 61),
			new TableEntry('Negotiation').withRoleInterval(62, 62),
			new TableEntry('Observation').withRoleInterval(63, 63),
			new TableEntry('Painting').withRoleInterval(64, 64),
			new TableEntry('Performance').withRoleInterval(65, 65),
			new TableEntry('Persuasion').withRoleInterval(66, 66),
			new TableEntry('Philosophy').withRoleInterval(67, 67),
			new TableEntry('Pickpocketing').withRoleInterval(68, 68),
			new TableEntry('Piloting').withRoleInterval(69, 69),
			new TableEntry('Poison-Making').withRoleInterval(70, 70),
			new TableEntry('Pottery').withRoleInterval(71, 71),
			new TableEntry('Reading-People').withRoleInterval(72, 72),
			new TableEntry('Religion').withRoleInterval(73, 73),
			new TableEntry('Research').withRoleInterval(74, 74),
			new TableEntry('Riding').withRoleInterval(75, 75),
			new TableEntry('Ritual-Magic').withRoleInterval(76, 76),
			new TableEntry('Rope-Work').withRoleInterval(77, 77),
			new TableEntry('Sailing').withRoleInterval(78, 78),
			new TableEntry('Scholarship').withRoleInterval(79, 79),
			new TableEntry('Sculpting').withRoleInterval(80, 80),
			new TableEntry('Seduction').withRoleInterval(81, 81),
			new TableEntry('Singing').withRoleInterval(82, 82),
			new TableEntry('Sleight-of-Hand').withRoleInterval(83, 83),
			new TableEntry('Smithing').withRoleInterval(84, 84),
			new TableEntry('Stealth').withRoleInterval(85, 85),
			new TableEntry('Stoneworking').withRoleInterval(86, 86),
			new TableEntry('Storytelling').withRoleInterval(87, 87),
			new TableEntry('Strategy').withRoleInterval(88, 88),
			new TableEntry('Survival').withRoleInterval(89, 89),
			new TableEntry('Swimming').withRoleInterval(90, 90),
			new TableEntry('Swordsmanship').withRoleInterval(91, 91),
			new TableEntry('Tactics').withRoleInterval(92, 92),
			new TableEntry('Tailoring').withRoleInterval(93, 93),
			new TableEntry('Thievery').withRoleInterval(94, 94),
			new TableEntry('Tracking').withRoleInterval(95, 95),
			new TableEntry('Trapping').withRoleInterval(96, 96),
			new TableEntry('Weaponcrafting').withRoleInterval(97, 97),
			new TableEntry('Weaving').withRoleInterval(98, 98),
			new TableEntry('Wilderness-Lore').withRoleInterval(99, 99),
			new TableEntry('Writing').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterSkills, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
