import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterConversationsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Accuses').withRoleInterval(1, 1),
			new TableEntry('Advises').withRoleInterval(2, 2),
			new TableEntry('Agrees').withRoleInterval(3, 3),
			new TableEntry('Analyzes').withRoleInterval(4, 4),
			new TableEntry('Apologizes').withRoleInterval(5, 5),
			new TableEntry('Argues').withRoleInterval(6, 6),
			new TableEntry('Asks').withRoleInterval(7, 7),
			new TableEntry('Begs').withRoleInterval(8, 8),
			new TableEntry('Boasts').withRoleInterval(9, 9),
			new TableEntry('Challenges').withRoleInterval(10, 10),
			new TableEntry('Chatters').withRoleInterval(11, 11),
			new TableEntry('Clarifies').withRoleInterval(12, 12),
			new TableEntry('Commands').withRoleInterval(13, 13),
			new TableEntry('Complains').withRoleInterval(14, 14),
			new TableEntry('Compliments').withRoleInterval(15, 15),
			new TableEntry('Confesses').withRoleInterval(16, 16),
			new TableEntry('Confides').withRoleInterval(17, 17),
			new TableEntry('Congratulates').withRoleInterval(18, 18),
			new TableEntry('Convinces').withRoleInterval(19, 19),
			new TableEntry('Criticizes').withRoleInterval(20, 20),
			new TableEntry('Curses').withRoleInterval(21, 21),
			new TableEntry('Debates').withRoleInterval(22, 22),
			new TableEntry('Declines').withRoleInterval(23, 23),
			new TableEntry('Defends').withRoleInterval(24, 24),
			new TableEntry('Demands').withRoleInterval(25, 25),
			new TableEntry('Denies').withRoleInterval(26, 26),
			new TableEntry('Describes').withRoleInterval(27, 27),
			new TableEntry('Dismisses').withRoleInterval(28, 28),
			new TableEntry('Encourages').withRoleInterval(29, 29),
			new TableEntry('Evades').withRoleInterval(30, 30),
			new TableEntry('Exaggerates').withRoleInterval(31, 31),
			new TableEntry('Exclaims').withRoleInterval(32, 32),
			new TableEntry('Explains').withRoleInterval(33, 33),
			new TableEntry('Flatters').withRoleInterval(34, 34),
			new TableEntry('Gossips').withRoleInterval(35, 35),
			new TableEntry('Greets').withRoleInterval(36, 36),
			new TableEntry('Grumbles').withRoleInterval(37, 37),
			new TableEntry('Hesitates').withRoleInterval(38, 38),
			new TableEntry('Hints').withRoleInterval(39, 39),
			new TableEntry('Ignores').withRoleInterval(40, 40),
			new TableEntry('Implies').withRoleInterval(41, 41),
			new TableEntry('Informs').withRoleInterval(42, 42),
			new TableEntry('Inquires').withRoleInterval(43, 43),
			new TableEntry('Insists').withRoleInterval(44, 44),
			new TableEntry('Insults').withRoleInterval(45, 45),
			new TableEntry('Interrogates').withRoleInterval(46, 46),
			new TableEntry('Interrupts').withRoleInterval(47, 47),
			new TableEntry('Intimidates').withRoleInterval(48, 48),
			new TableEntry('Invites').withRoleInterval(49, 49),
			new TableEntry('Jokes').withRoleInterval(50, 50),
			new TableEntry('Justifies').withRoleInterval(51, 51),
			new TableEntry('Laughs').withRoleInterval(52, 52),
			new TableEntry('Lectures').withRoleInterval(53, 53),
			new TableEntry('Lies').withRoleInterval(54, 54),
			new TableEntry('Listens').withRoleInterval(55, 55),
			new TableEntry('Mocks').withRoleInterval(56, 56),
			new TableEntry('Mumbles').withRoleInterval(57, 57),
			new TableEntry('Mutters').withRoleInterval(58, 58),
			new TableEntry('Negotiates').withRoleInterval(59, 59),
			new TableEntry('Nods').withRoleInterval(60, 60),
			new TableEntry('Objects').withRoleInterval(61, 61),
			new TableEntry('Offers').withRoleInterval(62, 62),
			new TableEntry('Orders').withRoleInterval(63, 63),
			new TableEntry('Persuades').withRoleInterval(64, 64),
			new TableEntry('Pleads').withRoleInterval(65, 65),
			new TableEntry('Ponders').withRoleInterval(66, 66),
			new TableEntry('Praises').withRoleInterval(67, 67),
			new TableEntry('Preaches').withRoleInterval(68, 68),
			new TableEntry('Promises').withRoleInterval(69, 69),
			new TableEntry('Prophesies').withRoleInterval(70, 70),
			new TableEntry('Proposes').withRoleInterval(71, 71),
			new TableEntry('Protests').withRoleInterval(72, 72),
			new TableEntry('Questions').withRoleInterval(73, 73),
			new TableEntry('Rambles').withRoleInterval(74, 74),
			new TableEntry('Reassures').withRoleInterval(75, 75),
			new TableEntry('Refuses').withRoleInterval(76, 76),
			new TableEntry('Reminisces').withRoleInterval(77, 77),
			new TableEntry('Reports').withRoleInterval(78, 78),
			new TableEntry('Requests').withRoleInterval(79, 79),
			new TableEntry('Reveals').withRoleInterval(80, 80),
			new TableEntry('Scolds').withRoleInterval(81, 81),
			new TableEntry('Shouts').withRoleInterval(82, 82),
			new TableEntry('Sighs').withRoleInterval(83, 83),
			new TableEntry('Speculates').withRoleInterval(84, 84),
			new TableEntry('Stammers').withRoleInterval(85, 85),
			new TableEntry('Suggests').withRoleInterval(86, 86),
			new TableEntry('Summarizes').withRoleInterval(87, 87),
			new TableEntry('Swears').withRoleInterval(88, 88),
			new TableEntry('Teaches').withRoleInterval(89, 89),
			new TableEntry('Teases').withRoleInterval(90, 90),
			new TableEntry('Tells-Story').withRoleInterval(91, 91),
			new TableEntry('Thanks').withRoleInterval(92, 92),
			new TableEntry('Threatens').withRoleInterval(93, 93),
			new TableEntry('Volunteers').withRoleInterval(94, 94),
			new TableEntry('Vows').withRoleInterval(95, 95),
			new TableEntry('Warns').withRoleInterval(96, 96),
			new TableEntry('Welcomes').withRoleInterval(97, 97),
			new TableEntry('Whines').withRoleInterval(98, 98),
			new TableEntry('Whispers').withRoleInterval(99, 99),
			new TableEntry('Yells').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterConversations, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
