import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

export class CharacterMotivationsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Acceptance').withRoleInterval(1, 1),
			new TableEntry('Achievement').withRoleInterval(2, 2),
			new TableEntry('Advancement').withRoleInterval(3, 3),
			new TableEntry('Adventure').withRoleInterval(4, 4),
			new TableEntry('Ambition').withRoleInterval(5, 5),
			new TableEntry('Atonement').withRoleInterval(6, 6),
			new TableEntry('Belonging').withRoleInterval(7, 7),
			new TableEntry('Benevolence').withRoleInterval(8, 8),
			new TableEntry('Compassion').withRoleInterval(9, 9),
			new TableEntry('Competition').withRoleInterval(10, 10),
			new TableEntry('Conquest').withRoleInterval(11, 11),
			new TableEntry('Control').withRoleInterval(12, 12),
			new TableEntry('Creation').withRoleInterval(13, 13),
			new TableEntry('Curiosity').withRoleInterval(14, 14),
			new TableEntry('Defiance').withRoleInterval(15, 15),
			new TableEntry('Desperation').withRoleInterval(16, 16),
			new TableEntry('Destiny').withRoleInterval(17, 17),
			new TableEntry('Discovery').withRoleInterval(18, 18),
			new TableEntry('Domination').withRoleInterval(19, 19),
			new TableEntry('Duty').withRoleInterval(20, 20),
			new TableEntry('Enlightenment').withRoleInterval(21, 21),
			new TableEntry('Escape').withRoleInterval(22, 22),
			new TableEntry('Excellence').withRoleInterval(23, 23),
			new TableEntry('Excitement').withRoleInterval(24, 24),
			new TableEntry('Faith').withRoleInterval(25, 25),
			new TableEntry('Fame').withRoleInterval(26, 26),
			new TableEntry('Family').withRoleInterval(27, 27),
			new TableEntry('Fear').withRoleInterval(28, 28),
			new TableEntry('Freedom').withRoleInterval(29, 29),
			new TableEntry('Friendship').withRoleInterval(30, 30),
			new TableEntry('Glory').withRoleInterval(31, 31),
			new TableEntry('Greed').withRoleInterval(32, 32),
			new TableEntry('Growth').withRoleInterval(33, 33),
			new TableEntry('Guilt').withRoleInterval(34, 34),
			new TableEntry('Happiness').withRoleInterval(35, 35),
			new TableEntry('Hatred').withRoleInterval(36, 36),
			new TableEntry('Honor').withRoleInterval(37, 37),
			new TableEntry('Hope').withRoleInterval(38, 38),
			new TableEntry('Identity').withRoleInterval(39, 39),
			new TableEntry('Independence').withRoleInterval(40, 40),
			new TableEntry('Influence').withRoleInterval(41, 41),
			new TableEntry('Innovation').withRoleInterval(42, 42),
			new TableEntry('Jealousy').withRoleInterval(43, 43),
			new TableEntry('Justice').withRoleInterval(44, 44),
			new TableEntry('Knowledge').withRoleInterval(45, 45),
			new TableEntry('Legacy').withRoleInterval(46, 46),
			new TableEntry('Liberty').withRoleInterval(47, 47),
			new TableEntry('Love').withRoleInterval(48, 48),
			new TableEntry('Loyalty').withRoleInterval(49, 49),
			new TableEntry('Mastery').withRoleInterval(50, 50),
			new TableEntry('Mystery').withRoleInterval(51, 51),
			new TableEntry('Obedience').withRoleInterval(52, 52),
			new TableEntry('Order').withRoleInterval(53, 53),
			new TableEntry('Peace').withRoleInterval(54, 54),
			new TableEntry('Perfection').withRoleInterval(55, 55),
			new TableEntry('Pleasure').withRoleInterval(56, 56),
			new TableEntry('Power').withRoleInterval(57, 57),
			new TableEntry('Pride').withRoleInterval(58, 58),
			new TableEntry('Progress').withRoleInterval(59, 59),
			new TableEntry('Prophecy').withRoleInterval(60, 60),
			new TableEntry('Protection').withRoleInterval(61, 61),
			new TableEntry('Purity').withRoleInterval(62, 62),
			new TableEntry('Purpose').withRoleInterval(63, 63),
			new TableEntry('Recognition').withRoleInterval(64, 64),
			new TableEntry('Redemption').withRoleInterval(65, 65),
			new TableEntry('Respect').withRoleInterval(66, 66),
			new TableEntry('Responsibility').withRoleInterval(67, 67),
			new TableEntry('Retribution').withRoleInterval(68, 68),
			new TableEntry('Revenge').withRoleInterval(69, 69),
			new TableEntry('Righteousness').withRoleInterval(70, 70),
			new TableEntry('Romance').withRoleInterval(71, 71),
			new TableEntry('Safety').withRoleInterval(72, 72),
			new TableEntry('Security').withRoleInterval(73, 73),
			new TableEntry('Self-Destruction').withRoleInterval(74, 74),
			new TableEntry('Self-Improvement').withRoleInterval(75, 75),
			new TableEntry('Service').withRoleInterval(76, 76),
			new TableEntry('Stability').withRoleInterval(77, 77),
			new TableEntry('Status').withRoleInterval(78, 78),
			new TableEntry('Strength').withRoleInterval(79, 79),
			new TableEntry('Success').withRoleInterval(80, 80),
			new TableEntry('Superiority').withRoleInterval(81, 81),
			new TableEntry('Survival').withRoleInterval(82, 82),
			new TableEntry('Tradition').withRoleInterval(83, 83),
			new TableEntry('Transcendence').withRoleInterval(84, 84),
			new TableEntry('Transformation').withRoleInterval(85, 85),
			new TableEntry('Truth').withRoleInterval(86, 86),
			new TableEntry('Understanding').withRoleInterval(87, 87),
			new TableEntry('Validation').withRoleInterval(88, 88),
			new TableEntry('Vanity').withRoleInterval(89, 89),
			new TableEntry('Vengeance').withRoleInterval(90, 90),
			new TableEntry('Victory').withRoleInterval(91, 91),
			new TableEntry('Virtue').withRoleInterval(92, 92),
			new TableEntry('Wanderlust').withRoleInterval(93, 93),
			new TableEntry('Wealth').withRoleInterval(94, 94),
			new TableEntry('Wisdom').withRoleInterval(95, 95),
			new TableEntry('Wonder').withRoleInterval(96, 96),
			new TableEntry('Worship').withRoleInterval(97, 97),
			new TableEntry('Wrath').withRoleInterval(98, 98),
			new TableEntry('Yearning').withRoleInterval(99, 99),
			new TableEntry('Zeal').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicCharacterMotivations, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
