import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

/**
 * Mythic GME Descriptions Table 2
 * Descriptive adjectives for creating meaning
 */
export class DescriptionsTable2 extends Table {
	constructor() {
		const entries = [
			new TableEntry('Abnormal').withRoleInterval(1, 1),
			new TableEntry('Amusing').withRoleInterval(2, 2),
			new TableEntry('Artificial').withRoleInterval(3, 3),
			new TableEntry('Average').withRoleInterval(4, 4),
			new TableEntry('Beautiful').withRoleInterval(5, 5),
			new TableEntry('Bizarre').withRoleInterval(6, 6),
			new TableEntry('Boring').withRoleInterval(7, 7),
			new TableEntry('Bright').withRoleInterval(8, 8),
			new TableEntry('Broken').withRoleInterval(9, 9),
			new TableEntry('Clean').withRoleInterval(10, 10),
			new TableEntry('Cold').withRoleInterval(11, 11),
			new TableEntry('Colorful').withRoleInterval(12, 12),
			new TableEntry('Colorless').withRoleInterval(13, 13),
			new TableEntry('Comforting').withRoleInterval(14, 14),
			new TableEntry('Creepy').withRoleInterval(15, 15),
			new TableEntry('Cute').withRoleInterval(16, 16),
			new TableEntry('Damaged').withRoleInterval(17, 17),
			new TableEntry('Dark').withRoleInterval(18, 18),
			new TableEntry('Defeated').withRoleInterval(19, 19),
			new TableEntry('Dirty').withRoleInterval(20, 20),
			new TableEntry('Disagreeable').withRoleInterval(21, 21),
			new TableEntry('Dry').withRoleInterval(22, 22),
			new TableEntry('Dull').withRoleInterval(23, 23),
			new TableEntry('Empty').withRoleInterval(24, 24),
			new TableEntry('Enormous').withRoleInterval(25, 25),
			new TableEntry('Extraordinary').withRoleInterval(26, 26),
			new TableEntry('Extravagant').withRoleInterval(27, 27),
			new TableEntry('Faded').withRoleInterval(28, 28),
			new TableEntry('Familiar').withRoleInterval(29, 29),
			new TableEntry('Fancy').withRoleInterval(30, 30),
			new TableEntry('Feeble').withRoleInterval(31, 31),
			new TableEntry('Festive').withRoleInterval(32, 32),
			new TableEntry('Flawless').withRoleInterval(33, 33),
			new TableEntry('Forlorn').withRoleInterval(34, 34),
			new TableEntry('Fragile').withRoleInterval(35, 35),
			new TableEntry('Fragrant').withRoleInterval(36, 36),
			new TableEntry('Fresh').withRoleInterval(37, 37),
			new TableEntry('Full').withRoleInterval(38, 38),
			new TableEntry('Glorious').withRoleInterval(39, 39),
			new TableEntry('Graceful').withRoleInterval(40, 40),
			new TableEntry('Hard').withRoleInterval(41, 41),
			new TableEntry('Harsh').withRoleInterval(42, 42),
			new TableEntry('Healthy').withRoleInterval(43, 43),
			new TableEntry('Heavy').withRoleInterval(44, 44),
			new TableEntry('Historical').withRoleInterval(45, 45),
			new TableEntry('Horrible').withRoleInterval(46, 46),
			new TableEntry('Important').withRoleInterval(47, 47),
			new TableEntry('Interesting').withRoleInterval(48, 48),
			new TableEntry('Juvenile').withRoleInterval(49, 49),
			new TableEntry('Lacking').withRoleInterval(50, 50),
			new TableEntry('Large').withRoleInterval(51, 51),
			new TableEntry('Lavish').withRoleInterval(52, 52),
			new TableEntry('Lean').withRoleInterval(53, 53),
			new TableEntry('Less').withRoleInterval(54, 54),
			new TableEntry('Lethal').withRoleInterval(55, 55),
			new TableEntry('Lively').withRoleInterval(56, 56),
			new TableEntry('Lonely').withRoleInterval(57, 57),
			new TableEntry('Lovely').withRoleInterval(58, 58),
			new TableEntry('Magnificent').withRoleInterval(59, 59),
			new TableEntry('Mature').withRoleInterval(60, 60),
			new TableEntry('Messy').withRoleInterval(61, 61),
			new TableEntry('Mighty').withRoleInterval(62, 62),
			new TableEntry('Military').withRoleInterval(63, 63),
			new TableEntry('Modern').withRoleInterval(64, 64),
			new TableEntry('Mundane').withRoleInterval(65, 65),
			new TableEntry('Mysterious').withRoleInterval(66, 66),
			new TableEntry('Natural').withRoleInterval(67, 67),
			new TableEntry('Normal').withRoleInterval(68, 68),
			new TableEntry('Odd').withRoleInterval(69, 69),
			new TableEntry('Old').withRoleInterval(70, 70),
			new TableEntry('Pale').withRoleInterval(71, 71),
			new TableEntry('Peaceful').withRoleInterval(72, 72),
			new TableEntry('Petite').withRoleInterval(73, 73),
			new TableEntry('Plain').withRoleInterval(74, 74),
			new TableEntry('Poor').withRoleInterval(75, 75),
			new TableEntry('Protective').withRoleInterval(76, 76),
			new TableEntry('Protective').withRoleInterval(77, 77),
			new TableEntry('Quaint').withRoleInterval(78, 78),
			new TableEntry('Rare').withRoleInterval(79, 79),
			new TableEntry('Reassuring').withRoleInterval(80, 80),
			new TableEntry('Remarkable').withRoleInterval(81, 81),
			new TableEntry('Rotten').withRoleInterval(82, 82),
			new TableEntry('Rough').withRoleInterval(83, 83),
			new TableEntry('Ruined').withRoleInterval(84, 84),
			new TableEntry('Rustic').withRoleInterval(85, 85),
			new TableEntry('Scary').withRoleInterval(86, 86),
			new TableEntry('Shocking').withRoleInterval(87, 87),
			new TableEntry('Simple').withRoleInterval(88, 88),
			new TableEntry('Small').withRoleInterval(89, 89),
			new TableEntry('Smooth').withRoleInterval(90, 90),
			new TableEntry('Soft').withRoleInterval(91, 91),
			new TableEntry('Strong').withRoleInterval(92, 92),
			new TableEntry('Stylish').withRoleInterval(93, 93),
			new TableEntry('Unpleasant').withRoleInterval(94, 94),
			new TableEntry('Valuable').withRoleInterval(95, 95),
			new TableEntry('Vibrant').withRoleInterval(96, 96),
			new TableEntry('Warm').withRoleInterval(97, 97),
			new TableEntry('Watery').withRoleInterval(98, 98),
			new TableEntry('Weak').withRoleInterval(99, 99),
			new TableEntry('Young').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicDescriptionsTable2, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
