import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

/**
 * Mythic GME Descriptions Table 1
 * Descriptive adverbs for creating meaning
 */
export class DescriptionsTable1 extends Table {
	constructor() {
		const entries = [
			new TableEntry('Adventurously').withRoleInterval(1, 1),
			new TableEntry('Aggressively').withRoleInterval(2, 2),
			new TableEntry('Anxiously').withRoleInterval(3, 3),
			new TableEntry('Awkwardly').withRoleInterval(4, 4),
			new TableEntry('Beautifully').withRoleInterval(5, 5),
			new TableEntry('Bleakly').withRoleInterval(6, 6),
			new TableEntry('Boldly').withRoleInterval(7, 7),
			new TableEntry('Bravely').withRoleInterval(8, 8),
			new TableEntry('Busily').withRoleInterval(9, 9),
			new TableEntry('Calmly').withRoleInterval(10, 10),
			new TableEntry('Carefully').withRoleInterval(11, 11),
			new TableEntry('Carelessly').withRoleInterval(12, 12),
			new TableEntry('Cautiously').withRoleInterval(13, 13),
			new TableEntry('Ceaselessly').withRoleInterval(14, 14),
			new TableEntry('Cheerfully').withRoleInterval(15, 15),
			new TableEntry('Combatively').withRoleInterval(16, 16),
			new TableEntry('Coolly').withRoleInterval(17, 17),
			new TableEntry('Crazily').withRoleInterval(18, 18),
			new TableEntry('Curiously').withRoleInterval(19, 19),
			new TableEntry('Dangerously').withRoleInterval(20, 20),
			new TableEntry('Defiantly').withRoleInterval(21, 21),
			new TableEntry('Deliberately').withRoleInterval(22, 22),
			new TableEntry('Delicately').withRoleInterval(23, 23),
			new TableEntry('Delightfully').withRoleInterval(24, 24),
			new TableEntry('Dimly').withRoleInterval(25, 25),
			new TableEntry('Efficiently').withRoleInterval(26, 26),
			new TableEntry('Emotionally').withRoleInterval(27, 27),
			new TableEntry('Energetically').withRoleInterval(28, 28),
			new TableEntry('Enormously').withRoleInterval(29, 29),
			new TableEntry('Enthusiastically').withRoleInterval(30, 30),
			new TableEntry('Excitedly').withRoleInterval(31, 31),
			new TableEntry('Fearfully').withRoleInterval(32, 32),
			new TableEntry('Ferociously').withRoleInterval(33, 33),
			new TableEntry('Fiercely').withRoleInterval(34, 34),
			new TableEntry('Foolishly').withRoleInterval(35, 35),
			new TableEntry('Fortunately').withRoleInterval(36, 36),
			new TableEntry('Frantically').withRoleInterval(37, 37),
			new TableEntry('Freely').withRoleInterval(38, 38),
			new TableEntry('Frighteningly').withRoleInterval(39, 39),
			new TableEntry('Fully').withRoleInterval(40, 40),
			new TableEntry('Generously').withRoleInterval(41, 41),
			new TableEntry('Gently').withRoleInterval(42, 42),
			new TableEntry('Gladly').withRoleInterval(43, 43),
			new TableEntry('Gracefully').withRoleInterval(44, 44),
			new TableEntry('Gratefully').withRoleInterval(45, 45),
			new TableEntry('Happily').withRoleInterval(46, 46),
			new TableEntry('Hastily').withRoleInterval(47, 47),
			new TableEntry('Healthily').withRoleInterval(48, 48),
			new TableEntry('Helpfully').withRoleInterval(49, 49),
			new TableEntry('Helplessly').withRoleInterval(50, 50),
			new TableEntry('Generously').withRoleInterval(51, 51),
			new TableEntry('Gently').withRoleInterval(52, 52),
			new TableEntry('Gladly').withRoleInterval(53, 53),
			new TableEntry('Gracefully').withRoleInterval(54, 54),
			new TableEntry('Gratefully').withRoleInterval(55, 55),
			new TableEntry('Happily').withRoleInterval(56, 56),
			new TableEntry('Hastily').withRoleInterval(57, 57),
			new TableEntry('Healthily').withRoleInterval(58, 58),
			new TableEntry('Helpfully').withRoleInterval(59, 59),
			new TableEntry('Helplessly').withRoleInterval(60, 60),
			new TableEntry('Hopelessly').withRoleInterval(61, 61),
			new TableEntry('Innocently').withRoleInterval(62, 62),
			new TableEntry('Intensely').withRoleInterval(63, 63),
			new TableEntry('Interestingly').withRoleInterval(64, 64),
			new TableEntry('Irritatingly').withRoleInterval(65, 65),
			new TableEntry('Joyfully').withRoleInterval(66, 66),
			new TableEntry('Kindly').withRoleInterval(67, 67),
			new TableEntry('Lazily').withRoleInterval(68, 68),
			new TableEntry('Lightly').withRoleInterval(69, 69),
			new TableEntry('Loosely').withRoleInterval(70, 70),
			new TableEntry('Loudly').withRoleInterval(71, 71),
			new TableEntry('Lovingly').withRoleInterval(72, 72),
			new TableEntry('Loyally').withRoleInterval(73, 73),
			new TableEntry('Majestically').withRoleInterval(74, 74),
			new TableEntry('Meaningfully').withRoleInterval(75, 75),
			new TableEntry('Officially').withRoleInterval(76, 76),
			new TableEntry('Partially').withRoleInterval(77, 77),
			new TableEntry('Passively').withRoleInterval(78, 78),
			new TableEntry('Peacefully').withRoleInterval(79, 79),
			new TableEntry('Perfectly').withRoleInterval(80, 80),
			new TableEntry('Playfully').withRoleInterval(81, 81),
			new TableEntry('Politely').withRoleInterval(82, 82),
			new TableEntry('Positively').withRoleInterval(83, 83),
			new TableEntry('Powerfully').withRoleInterval(84, 84),
			new TableEntry('Quaintly').withRoleInterval(85, 85),
			new TableEntry('Quarrelsomely').withRoleInterval(86, 86),
			new TableEntry('Quietly').withRoleInterval(87, 87),
			new TableEntry('Roughly').withRoleInterval(88, 88),
			new TableEntry('Rudely').withRoleInterval(89, 89),
			new TableEntry('Ruthlessly').withRoleInterval(90, 90),
			new TableEntry('Slowly').withRoleInterval(91, 91),
			new TableEntry('Softly').withRoleInterval(92, 92),
			new TableEntry('Strangely').withRoleInterval(93, 93),
			new TableEntry('Swiftly').withRoleInterval(94, 94),
			new TableEntry('Threateningly').withRoleInterval(95, 95),
			new TableEntry('Timidly').withRoleInterval(96, 96),
			new TableEntry('Very').withRoleInterval(97, 97),
			new TableEntry('Violently').withRoleInterval(98, 98),
			new TableEntry('Wildly').withRoleInterval(99, 99),
			new TableEntry('Yieldingly').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicDescriptionsTable1, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
