import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

/**
 * Mythic GME Locations Elements Table
 * Location descriptors for creating meaning
 */
export class LocationsElementsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Abandoned').withRoleInterval(1, 1),
			new TableEntry('Active').withRoleInterval(2, 2),
			new TableEntry('Artistic').withRoleInterval(3, 3),
			new TableEntry('Atmosphere').withRoleInterval(4, 4),
			new TableEntry('Beautiful').withRoleInterval(5, 5),
			new TableEntry('Bleak').withRoleInterval(6, 6),
			new TableEntry('Bright').withRoleInterval(7, 7),
			new TableEntry('Business').withRoleInterval(8, 8),
			new TableEntry('Calm').withRoleInterval(9, 9),
			new TableEntry('Charming').withRoleInterval(10, 10),
			new TableEntry('Clean').withRoleInterval(11, 11),
			new TableEntry('Cluttered').withRoleInterval(12, 12),
			new TableEntry('Cold').withRoleInterval(13, 13),
			new TableEntry('Colorful').withRoleInterval(14, 14),
			new TableEntry('Colorless').withRoleInterval(15, 15),
			new TableEntry('Confusing').withRoleInterval(16, 16),
			new TableEntry('Cramped').withRoleInterval(17, 17),
			new TableEntry('Creepy').withRoleInterval(18, 18),
			new TableEntry('Crude').withRoleInterval(19, 19),
			new TableEntry('Cute').withRoleInterval(20, 20),
			new TableEntry('Damaged').withRoleInterval(21, 21),
			new TableEntry('Dangerous').withRoleInterval(22, 22),
			new TableEntry('Dark').withRoleInterval(23, 23),
			new TableEntry('Delightful').withRoleInterval(24, 24),
			new TableEntry('Dirty').withRoleInterval(25, 25),
			new TableEntry('Domestic').withRoleInterval(26, 26),
			new TableEntry('Empty').withRoleInterval(27, 27),
			new TableEntry('Enclosed').withRoleInterval(28, 28),
			new TableEntry('Enormous').withRoleInterval(29, 29),
			new TableEntry('Entrance').withRoleInterval(30, 30),
			new TableEntry('Exclusive').withRoleInterval(31, 31),
			new TableEntry('Exposed').withRoleInterval(32, 32),
			new TableEntry('Extravagant').withRoleInterval(33, 33),
			new TableEntry('Familiar').withRoleInterval(34, 34),
			new TableEntry('Fancy').withRoleInterval(35, 35),
			new TableEntry('Festive').withRoleInterval(36, 36),
			new TableEntry('Foreboding').withRoleInterval(37, 37),
			new TableEntry('Fortunate').withRoleInterval(38, 38),
			new TableEntry('Fragrant').withRoleInterval(39, 39),
			new TableEntry('Frantic').withRoleInterval(40, 40),
			new TableEntry('Frightening').withRoleInterval(41, 41),
			new TableEntry('Full').withRoleInterval(42, 42),
			new TableEntry('Harmful').withRoleInterval(43, 43),
			new TableEntry('Helpful').withRoleInterval(44, 44),
			new TableEntry('Horrible').withRoleInterval(45, 45),
			new TableEntry('Important').withRoleInterval(46, 46),
			new TableEntry('Impressive').withRoleInterval(47, 47),
			new TableEntry('Inactive').withRoleInterval(48, 48),
			new TableEntry('Intense').withRoleInterval(49, 49),
			new TableEntry('Intriguing').withRoleInterval(50, 50),
			new TableEntry('Lively').withRoleInterval(51, 51),
			new TableEntry('Lonely').withRoleInterval(52, 52),
			new TableEntry('Long').withRoleInterval(53, 53),
			new TableEntry('Loud').withRoleInterval(54, 54),
			new TableEntry('Meaningful').withRoleInterval(55, 55),
			new TableEntry('Messy').withRoleInterval(56, 56),
			new TableEntry('Mobile').withRoleInterval(57, 57),
			new TableEntry('Modern').withRoleInterval(58, 58),
			new TableEntry('Mundane').withRoleInterval(59, 59),
			new TableEntry('Mysterious').withRoleInterval(60, 60),
			new TableEntry('Natural').withRoleInterval(61, 61),
			new TableEntry('New').withRoleInterval(62, 62),
			new TableEntry('Occupied').withRoleInterval(63, 63),
			new TableEntry('Odd').withRoleInterval(64, 64),
			new TableEntry('Official').withRoleInterval(65, 65),
			new TableEntry('Old').withRoleInterval(66, 66),
			new TableEntry('Open').withRoleInterval(67, 67),
			new TableEntry('Peaceful').withRoleInterval(68, 68),
			new TableEntry('Personal').withRoleInterval(69, 69),
			new TableEntry('Plain').withRoleInterval(70, 70),
			new TableEntry('Portal').withRoleInterval(71, 71),
			new TableEntry('Protected').withRoleInterval(72, 72),
			new TableEntry('Protection').withRoleInterval(73, 73),
			new TableEntry('Purposeful').withRoleInterval(74, 74),
			new TableEntry('Quiet').withRoleInterval(75, 75),
			new TableEntry('Protected').withRoleInterval(76, 76),
			new TableEntry('Protection').withRoleInterval(77, 77),
			new TableEntry('Purposeful').withRoleInterval(78, 78),
			new TableEntry('Quiet').withRoleInterval(79, 79),
			new TableEntry('Reassuring').withRoleInterval(80, 80),
			new TableEntry('Remote').withRoleInterval(81, 81),
			new TableEntry('Resourceful').withRoleInterval(82, 82),
			new TableEntry('Ruined').withRoleInterval(83, 83),
			new TableEntry('Rustic').withRoleInterval(84, 84),
			new TableEntry('Safe').withRoleInterval(85, 85),
			new TableEntry('Services').withRoleInterval(86, 86),
			new TableEntry('Simple').withRoleInterval(87, 87),
			new TableEntry('Small').withRoleInterval(88, 88),
			new TableEntry('Spacious').withRoleInterval(89, 89),
			new TableEntry('Storage').withRoleInterval(90, 90),
			new TableEntry('Strange').withRoleInterval(91, 91),
			new TableEntry('Stylish').withRoleInterval(92, 92),
			new TableEntry('Suspicious').withRoleInterval(93, 93),
			new TableEntry('Tall').withRoleInterval(94, 94),
			new TableEntry('Threatening').withRoleInterval(95, 95),
			new TableEntry('Tranquil').withRoleInterval(96, 96),
			new TableEntry('Unexpected').withRoleInterval(97, 97),
			new TableEntry('Unpleasant').withRoleInterval(98, 98),
			new TableEntry('Unusual').withRoleInterval(99, 99),
			new TableEntry('Useful').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicLocationsElements, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
