import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';
import { TableType } from '../tableType';
import { DiceRole } from '../diceRole';

/**
 * Mythic GME Objects Elements Table
 * Object descriptors for creating meaning
 */
export class ObjectsElementsTable extends Table {
	constructor() {
		const entries = [
			new TableEntry('Active').withRoleInterval(1, 1),
			new TableEntry('Artistic').withRoleInterval(2, 2),
			new TableEntry('Average').withRoleInterval(3, 3),
			new TableEntry('Beautiful').withRoleInterval(4, 4),
			new TableEntry('Bizarre').withRoleInterval(5, 5),
			new TableEntry('Bright').withRoleInterval(6, 6),
			new TableEntry('Clothing').withRoleInterval(7, 7),
			new TableEntry('Clue').withRoleInterval(8, 8),
			new TableEntry('Cold').withRoleInterval(9, 9),
			new TableEntry('Colorful').withRoleInterval(10, 10),
			new TableEntry('Communication').withRoleInterval(11, 11),
			new TableEntry('Complicated').withRoleInterval(12, 12),
			new TableEntry('Confusing').withRoleInterval(13, 13),
			new TableEntry('Consumable').withRoleInterval(14, 14),
			new TableEntry('Container').withRoleInterval(15, 15),
			new TableEntry('Creepy').withRoleInterval(16, 16),
			new TableEntry('Crude').withRoleInterval(17, 17),
			new TableEntry('Cute').withRoleInterval(18, 18),
			new TableEntry('Damaged').withRoleInterval(19, 19),
			new TableEntry('Dangerous').withRoleInterval(20, 20),
			new TableEntry('Deactivated').withRoleInterval(21, 21),
			new TableEntry('Deliberate').withRoleInterval(22, 22),
			new TableEntry('Delightful').withRoleInterval(23, 23),
			new TableEntry('Desired').withRoleInterval(24, 24),
			new TableEntry('Domestic').withRoleInterval(25, 25),
			new TableEntry('Empty').withRoleInterval(26, 26),
			new TableEntry('Energy').withRoleInterval(27, 27),
			new TableEntry('Enormous').withRoleInterval(28, 28),
			new TableEntry('Equipment').withRoleInterval(29, 29),
			new TableEntry('Expected').withRoleInterval(30, 30),
			new TableEntry('Expended').withRoleInterval(31, 31),
			new TableEntry('Extravagant').withRoleInterval(32, 32),
			new TableEntry('Faded').withRoleInterval(33, 33),
			new TableEntry('Familiar').withRoleInterval(34, 34),
			new TableEntry('Fancy').withRoleInterval(35, 35),
			new TableEntry('Flora').withRoleInterval(36, 36),
			new TableEntry('Fortunate').withRoleInterval(37, 37),
			new TableEntry('Fragile').withRoleInterval(38, 38),
			new TableEntry('Fragrant').withRoleInterval(39, 39),
			new TableEntry('Frightening').withRoleInterval(40, 40),
			new TableEntry('Garbage').withRoleInterval(41, 41),
			new TableEntry('Guidance').withRoleInterval(42, 42),
			new TableEntry('Hard').withRoleInterval(43, 43),
			new TableEntry('Harmful').withRoleInterval(44, 44),
			new TableEntry('Healing').withRoleInterval(45, 45),
			new TableEntry('Heavy').withRoleInterval(46, 46),
			new TableEntry('Helpful').withRoleInterval(47, 47),
			new TableEntry('Horrible').withRoleInterval(48, 48),
			new TableEntry('Important').withRoleInterval(49, 49),
			new TableEntry('Inactive').withRoleInterval(50, 50),
			new TableEntry('Information').withRoleInterval(51, 51),
			new TableEntry('Intriguing').withRoleInterval(52, 52),
			new TableEntry('Large').withRoleInterval(53, 53),
			new TableEntry('Lethal').withRoleInterval(54, 54),
			new TableEntry('Light').withRoleInterval(55, 55),
			new TableEntry('Liquid').withRoleInterval(56, 56),
			new TableEntry('Loud').withRoleInterval(57, 57),
			new TableEntry('Majestic').withRoleInterval(58, 58),
			new TableEntry('Meaningful').withRoleInterval(59, 59),
			new TableEntry('Mechanical').withRoleInterval(60, 60),
			new TableEntry('Modern').withRoleInterval(61, 61),
			new TableEntry('Moving').withRoleInterval(62, 62),
			new TableEntry('Multiple').withRoleInterval(63, 63),
			new TableEntry('Mundane').withRoleInterval(64, 64),
			new TableEntry('Mysterious').withRoleInterval(65, 65),
			new TableEntry('Natural').withRoleInterval(66, 66),
			new TableEntry('New').withRoleInterval(67, 67),
			new TableEntry('Odd').withRoleInterval(68, 68),
			new TableEntry('Official').withRoleInterval(69, 69),
			new TableEntry('Old').withRoleInterval(70, 70),
			new TableEntry('Ornamental').withRoleInterval(71, 71),
			new TableEntry('Ornate').withRoleInterval(72, 72),
			new TableEntry('Personal').withRoleInterval(73, 73),
			new TableEntry('Powerful').withRoleInterval(74, 74),
			new TableEntry('Prized').withRoleInterval(75, 75),
			new TableEntry('Protection').withRoleInterval(76, 76),
			new TableEntry('Rare').withRoleInterval(77, 77),
			new TableEntry('Ready').withRoleInterval(78, 78),
			new TableEntry('Reassuring').withRoleInterval(79, 79),
			new TableEntry('Resource').withRoleInterval(80, 80),
			new TableEntry('Ruined').withRoleInterval(81, 81),
			new TableEntry('Small').withRoleInterval(82, 82),
			new TableEntry('Soft').withRoleInterval(83, 83),
			new TableEntry('Solitary').withRoleInterval(84, 84),
			new TableEntry('Stolen').withRoleInterval(85, 85),
			new TableEntry('Strange').withRoleInterval(86, 86),
			new TableEntry('Stylish').withRoleInterval(87, 87),
			new TableEntry('Threatening').withRoleInterval(88, 88),
			new TableEntry('Tool').withRoleInterval(89, 89),
			new TableEntry('Travel').withRoleInterval(90, 90),
			new TableEntry('Unexpected').withRoleInterval(91, 91),
			new TableEntry('Unpleasant').withRoleInterval(92, 92),
			new TableEntry('Unusual').withRoleInterval(93, 93),
			new TableEntry('Useful').withRoleInterval(94, 94),
			new TableEntry('Useless').withRoleInterval(95, 95),
			new TableEntry('Valuable').withRoleInterval(96, 96),
			new TableEntry('Warm').withRoleInterval(97, 97),
			new TableEntry('Weapon').withRoleInterval(98, 98),
			new TableEntry('Wet').withRoleInterval(99, 99),
			new TableEntry('Worn').withRoleInterval(100, 100)
		];

		super(entries, TableTitles.MythicObjectsElements, TableType.SoloRPG, new DiceRole(1, 100));
	}
}
