import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class AfricanNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Abatu"))
        entries.push(new TableEntry("Akanea"))
        entries.push(new TableEntry("Aktivi"))
        entries.push(new TableEntry("Alre-Go"))
        entries.push(new TableEntry("Alunga"))
        entries.push(new TableEntry("Amima"))
        entries.push(new TableEntry("Anakena"))
        entries.push(new TableEntry("Anekka-Ka"))
        entries.push(new TableEntry("Ariki"))
        entries.push(new TableEntry("Asmoa"))
        entries.push(new TableEntry("Ataranga"))
        entries.push(new TableEntry("Bakiri"))
        entries.push(new TableEntry("Dasu"))
        entries.push(new TableEntry("Dawa"))
        entries.push(new TableEntry("Dpao"))
        entries.push(new TableEntry("Ekaro"))
        entries.push(new TableEntry("Esla"))
        entries.push(new TableEntry("Fekka"))
        entries.push(new TableEntry("Hahi"))
        entries.push(new TableEntry("Hoa"))
        entries.push(new TableEntry("Jaja"))
        entries.push(new TableEntry("Babumba"))
        entries.push(new TableEntry("Jemima"))
        entries.push(new TableEntry("Ka"))
        entries.push(new TableEntry("Kalu"))
        entries.push(new TableEntry("Kamali"))
        entries.push(new TableEntry("Katinga"))
        entries.push(new TableEntry("Khaikhai"))
        entries.push(new TableEntry("Kiri"))
        entries.push(new TableEntry("Kohao"))
        entries.push(new TableEntry("Kptanu"))
        entries.push(new TableEntry("Kumtami"))
        entries.push(new TableEntry("Kupe"))
        entries.push(new TableEntry("Lante"))
        entries.push(new TableEntry("Lisu"))
        entries.push(new TableEntry("Lolae"))
        entries.push(new TableEntry("Lupao"))
        entries.push(new TableEntry("Makkika"))
        entries.push(new TableEntry("Manisa"))
        entries.push(new TableEntry("Manui"))
        entries.push(new TableEntry("Manutara"))
        entries.push(new TableEntry("Mina-Moa"))
        entries.push(new TableEntry("Minoma"))
        entries.push(new TableEntry("Miraro"))
        entries.push(new TableEntry("Miru"))
        entries.push(new TableEntry("Muna"))
        entries.push(new TableEntry("Nahimi"))
        entries.push(new TableEntry("Nimuh"))
        entries.push(new TableEntry("Nimou"))
        entries.push(new TableEntry("Niwu"))
        entries.push(new TableEntry("Nuso-Nu"))
        entries.push(new TableEntry("Onigo"))
        entries.push(new TableEntry("Piku"))
        entries.push(new TableEntry("Pria-Papap"))
        entries.push(new TableEntry("Rangi"))
        entries.push(new TableEntry("Rasuli"))
        entries.push(new TableEntry("Ratan"))
        entries.push(new TableEntry("Rawiri"))
        entries.push(new TableEntry("Riro"))
        entries.push(new TableEntry("Roniga"))
        entries.push(new TableEntry("Rotang"))
        entries.push(new TableEntry("Safu"))
        entries.push(new TableEntry("Sama"))
        entries.push(new TableEntry("Sapa"))
        entries.push(new TableEntry("Satoh"))
        entries.push(new TableEntry("Simo"))
        entries.push(new TableEntry("Simu"))
        entries.push(new TableEntry("Swiwa"))
        entries.push(new TableEntry("Taaro"))
        entries.push(new TableEntry("Tahai"))
        entries.push(new TableEntry("Tare"))
        entries.push(new TableEntry("Temura"))
        entries.push(new TableEntry("Tipo-Tapo"))
        entries.push(new TableEntry("Totora"))
        entries.push(new TableEntry("Trana"))
        entries.push(new TableEntry("Uluruh"))
        entries.push(new TableEntry("Una"))
        entries.push(new TableEntry("Uriga"))
        entries.push(new TableEntry("Wela"))
        entries.push(new TableEntry("Wipati"))
        entries.push(new TableEntry("Yacar"))
        entries.push(new TableEntry("Yimari"))
        entries.push(new TableEntry("Yuta"))
        super(entries, TableTitles.AfricanName);
        this.tableType = TableType.Other;
    }
}