import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class ArabicMaleNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Abdul")
            )
        entries.push(new TableEntry("Abu")
            )
        entries.push(new TableEntry("Achmad")
            )
        entries.push(new TableEntry("Achmed")
            )
        entries.push(new TableEntry("Achtev")
            )
        entries.push(new TableEntry("Adil")
            )
        entries.push(new TableEntry("Ahmedin")
            )
        entries.push(new TableEntry("Akim")
            )
        entries.push(new TableEntry("Akram")
            )
        entries.push(new TableEntry("Alam")
            )
        entries.push(new TableEntry("Alev")
            )
        entries.push(new TableEntry("Ali")
            )
        entries.push(new TableEntry("Alrik")
            )
        entries.push(new TableEntry("Amaryd")
            )
        entries.push(new TableEntry("Amir")
            )
        entries.push(new TableEntry("Amjad")
            )
        entries.push(new TableEntry("Arkos")
            )
        entries.push(new TableEntry("Asad")
            )
        entries.push(new TableEntry("Asim")
            )
        entries.push(new TableEntry("ASsaf")
            )
        entries.push(new TableEntry("Aytan")
            )
        entries.push(new TableEntry("Azhar")
            )
        entries.push(new TableEntry("Azim")
            )
        entries.push(new TableEntry("Baba")
            )
        entries.push(new TableEntry("Babur")
            )
        entries.push(new TableEntry("Bachtar")
            )
        entries.push(new TableEntry("Bahir"))
        entries.push(new TableEntry("Basir")
            )
        entries.push(new TableEntry("Basman")
            )
        entries.push(new TableEntry("Banayman")
            )
        entries.push(new TableEntry("Bey")
            )
        entries.push(new TableEntry("Chadim")
            )
        entries.push(new TableEntry("Chaled")
            )
        entries.push(new TableEntry("Chamza")
            )
        entries.push(new TableEntry("Charez")
            )
        entries.push(new TableEntry("Charim")
            )
        entries.push(new TableEntry("Chassan")
            )
        entries.push(new TableEntry("Cherek")
            )
        entries.push(new TableEntry("Chatin")
            )
        entries.push(new TableEntry("Dajin")
            )
        entries.push(new TableEntry("Dawud")
            )
        entries.push(new TableEntry("Dunchaban")
            )
        entries.push(new TableEntry("Dilhaban")
            )
        entries.push(new TableEntry("Dschadir")
            )
        entries.push(new TableEntry("Dscherid")
            )
        entries.push(new TableEntry("Erkhaban")
            )
        entries.push(new TableEntry("Eslam"))
        entries.push(new TableEntry("Fahd")
            )
        entries.push(new TableEntry("Faiz")
            )
        entries.push(new TableEntry("Faizal")
            )
        entries.push(new TableEntry("Faramud"))
        entries.push(new TableEntry("Farsid"))
        entries.push(new TableEntry("Faruk"))
        entries.push(new TableEntry("Fathi"))
        entries.push(new TableEntry("Feruzef"))
        entries.push(new TableEntry("Feyhach"))
        entries.push(new TableEntry("Ftaihif"))
        entries.push(new TableEntry("Gaftar"))
        entries.push(new TableEntry("Ghulam"))
        entries.push(new TableEntry("Habib"))
        entries.push(new TableEntry("Habled"))
        entries.push(new TableEntry("Hamud"))
        entries.push(new TableEntry("Haimamud"))
        entries.push(new TableEntry("Hairan"))
        entries.push(new TableEntry("Hakim"))
        entries.push(new TableEntry("Hamar"))
        entries.push(new TableEntry("Hamed"))
        entries.push(new TableEntry("Hamid"))
        entries.push(new TableEntry("Hamil"))
        entries.push(new TableEntry("Hasrabal"))
        entries.push(new TableEntry("Hakim"))
        entries.push(new TableEntry("Haschnabah"))
        entries.push(new TableEntry("Hashim"))
        entries.push(new TableEntry("Hassan"))
        entries.push(new TableEntry("Hilal"))
        entries.push(new TableEntry("Hüssein"))
        entries.push(new TableEntry("Issam"))
        entries.push(new TableEntry("Jabir"))
        entries.push(new TableEntry("Jababib"))
        entries.push(new TableEntry("Khadir"))
        entries.push(new TableEntry("Kashban"))
        entries.push(new TableEntry("Kasim"))
        entries.push(new TableEntry("Kazam"))
        entries.push(new TableEntry("Kemal"))
        entries.push(new TableEntry("Khabla"))
        entries.push(new TableEntry("Khadil"))
        entries.push(new TableEntry("Khajid"))
        entries.push(new TableEntry("Khalid"))
        entries.push(new TableEntry("Khalil"))
        entries.push(new TableEntry("Khorim"))
        entries.push(new TableEntry("Khusrau"))
        entries.push(new TableEntry("Machmud"))
        entries.push(new TableEntry("Mahir"))
        entries.push(new TableEntry("Mahmud"))
        entries.push(new TableEntry("Malik"))
        entries.push(new TableEntry("Mansur"))
        entries.push(new TableEntry("Marwan"))
        entries.push(new TableEntry("Mawud"))
        entries.push(new TableEntry("Melekh"))
        entries.push(new TableEntry("Mezzek"))
        entries.push(new TableEntry("Mhadul"))
        entries.push(new TableEntry("Mhanach"))
        entries.push(new TableEntry("Maharbal"))
        entries.push(new TableEntry("Mhukkadin"))
        entries.push(new TableEntry("Mordai"))
        entries.push(new TableEntry("Muammar"))
        entries.push(new TableEntry("Murad"))
        entries.push(new TableEntry("Mussad"))
        entries.push(new TableEntry("Mustafa"))
        entries.push(new TableEntry("Nadim"))
        entries.push(new TableEntry("Madrash"))
        entries.push(new TableEntry("Nareb"))
        entries.push(new TableEntry("Nasim"))
        entries.push(new TableEntry("Nasir"))
        entries.push(new TableEntry("Omar"))
        entries.push(new TableEntry("Rachman"))
        entries.push(new TableEntry("Rafid"))
        entries.push(new TableEntry("Rahim"))
        entries.push(new TableEntry("Rashar"))
        entries.push(new TableEntry("Rashid"))
        entries.push(new TableEntry("Rashim"))
        entries.push(new TableEntry("Rasthul"))
        entries.push(new TableEntry("Rastafan"))
        entries.push(new TableEntry("Rahul"))
        entries.push(new TableEntry("Rechan"))
        entries.push(new TableEntry("Rezzan"))
        entries.push(new TableEntry("Rohal"))
        entries.push(new TableEntry("Ruban"))
        entries.push(new TableEntry("Ruchan"))
        entries.push(new TableEntry("Sadir"))
        entries.push(new TableEntry("Sahil"))
        entries.push(new TableEntry("Said"))
        entries.push(new TableEntry("Saiman"))
        entries.push(new TableEntry("Sali"))
        entries.push(new TableEntry("Sanshied"))
        entries.push(new TableEntry("Shafir"))
        entries.push(new TableEntry("Shakir"))
        entries.push(new TableEntry("Surkan"))
        entries.push(new TableEntry("Tahir"))
        entries.push(new TableEntry("Tarek"))
        entries.push(new TableEntry("Thamir"))
        entries.push(new TableEntry("Thulachim"))
        entries.push(new TableEntry("Umran"))
        entries.push(new TableEntry("Ukhraban"))
        entries.push(new TableEntry("Umar"))
        entries.push(new TableEntry("Yassir"))
        entries.push(new TableEntry("Yelmiz"))
        entries.push(new TableEntry("Yerdawan"))
        entries.push(new TableEntry("Yussuf"))
        entries.push(new TableEntry("Zachaban"))
        entries.push(new TableEntry("Zachan"))
        entries.push(new TableEntry("Zahir"))
        entries.push(new TableEntry("Zelhiman"))
        entries.push(new TableEntry("Zuhal"))
        entries.push(new TableEntry("Zulhamid"))
        super(entries, TableTitles.ArabicMaleName);
        this.tableType = TableType.Other;
    }
}