import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class BarbaricFemaleNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Aesa"))
        entries.push(new TableEntry("Andraga"))
        entries.push(new TableEntry("Aruleyd"))
        entries.push(new TableEntry("Bebann"))
        entries.push(new TableEntry("Blotlind"))
        entries.push(new TableEntry("Borrgach"))
        entries.push(new TableEntry("Brona"))
        entries.push(new TableEntry("Brucha"))
        entries.push(new TableEntry("Caltha"))
        entries.push(new TableEntry("Cirnach"))
        entries.push(new TableEntry("Corrja"))
        entries.push(new TableEntry("Dairdra"))
        entries.push(new TableEntry("Dundana"))
        entries.push(new TableEntry("Dunyabra"))
        entries.push(new TableEntry("Durrcha"))
        entries.push(new TableEntry("Eirnird"))
        entries.push(new TableEntry("Frunia"))
        entries.push(new TableEntry("Froya"))
        entries.push(new TableEntry("Gardrah"))
        entries.push(new TableEntry("Gharya"))
        entries.push(new TableEntry("Gjayka"))
        entries.push(new TableEntry("Grainme"))
        entries.push(new TableEntry("Griadhra"))
        entries.push(new TableEntry("Grimheyd"))
        entries.push(new TableEntry("Griwera"))
        entries.push(new TableEntry("Hachwa"))
        entries.push(new TableEntry("Hagwa"))
        entries.push(new TableEntry("Harrwa"))
        entries.push(new TableEntry("Hiltu"))
        entries.push(new TableEntry("Hjalbeth"))
        entries.push(new TableEntry("Hulga"))
        entries.push(new TableEntry("Ifnar"))
        entries.push(new TableEntry("Ifrunna"))
        entries.push(new TableEntry("Irfraid"))
        entries.push(new TableEntry("Keirnath"))
        entries.push(new TableEntry("Lurga"))
        entries.push(new TableEntry("Madhreth"))
        entries.push(new TableEntry("Margraidh"))
        entries.push(new TableEntry("Marthai"))
        entries.push(new TableEntry("Marwen"))
        entries.push(new TableEntry("Marzagh"))
        entries.push(new TableEntry("Megrim"))
        entries.push(new TableEntry("Milbeth"))
        entries.push(new TableEntry("Miharra"))
        entries.push(new TableEntry("Moirya"))
        entries.push(new TableEntry("Mordagmar"))
        entries.push(new TableEntry("Morrga"))
        entries.push(new TableEntry("Rachnaid"))
        entries.push(new TableEntry("Uthra"))
        entries.push(new TableEntry("Yrrwa"))
        entries.push(new TableEntry("Yuchgard"))
        entries.push(new TableEntry("Ywen"))
        entries.push(new TableEntry("Zurakka"))
        entries.push(new TableEntry("Artuna"))
        entries.push(new TableEntry("Ashirut"))
        entries.push(new TableEntry("DurGhacha"))
        entries.push(new TableEntry("Kcharra"))
        entries.push(new TableEntry("Rhazzeshta"))
        entries.push(new TableEntry("Shulmacha"))
        entries.push(new TableEntry("Taschara"))
        entries.push(new TableEntry("Uchazu"))
        entries.push(new TableEntry("ZulArtun"))
        super(entries, TableTitles.BarbaricFemaleName);
        this.tableType = TableType.Other;
    }
}