import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class BarbaricMaleNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Achzul"))
        entries.push(new TableEntry("Alzaar"))
        entries.push(new TableEntry("Arachtoch"))
        entries.push(new TableEntry("Ashur"))
        entries.push(new TableEntry("Bashoth"))
        entries.push(new TableEntry("Bardruck"))
        entries.push(new TableEntry("Dabrush"))
        entries.push(new TableEntry("Dorkach"))
        entries.push(new TableEntry("Moqtach"))
        entries.push(new TableEntry("Rhazzar"))
        entries.push(new TableEntry("Rochan"))
        entries.push(new TableEntry("Trachan"))
        entries.push(new TableEntry("Zerasuul"))
        entries.push(new TableEntry("Zuldamach"))
        entries.push(new TableEntry("Anargh"))
        entries.push(new TableEntry("Anchas"))
        entries.push(new TableEntry("Artach"))
        entries.push(new TableEntry("Balfoch"))
        entries.push(new TableEntry("Bartakh"))
        entries.push(new TableEntry("Breac"))
        entries.push(new TableEntry("Brein"))
        entries.push(new TableEntry("Caefynh"))
        entries.push(new TableEntry("Cainnoch"))
        entries.push(new TableEntry("Cammruh"))
        entries.push(new TableEntry("Branduch"))
        entries.push(new TableEntry("Derwech"))
        entries.push(new TableEntry("Druan"))
        entries.push(new TableEntry("Donnachadh"))
        entries.push(new TableEntry("Dundoch"))
        entries.push(new TableEntry("Etzel"))
        entries.push(new TableEntry("Firnwar"))
        entries.push(new TableEntry("Friedür"))
        entries.push(new TableEntry("Gabran"))
        entries.push(new TableEntry("Gaschnig"))
        entries.push(new TableEntry("Gedwed"))
        entries.push(new TableEntry("Hagwar"))
        entries.push(new TableEntry("Harutoch"))
        entries.push(new TableEntry("Harveg"))
        entries.push(new TableEntry("Hjalldür"))
        entries.push(new TableEntry("Ifrunndoch"))
        entries.push(new TableEntry("Islogh"))
        entries.push(new TableEntry("Siegmoch"))
        entries.push(new TableEntry("Kazan"))
        entries.push(new TableEntry("Lurasch"))
        entries.push(new TableEntry("Madadhskoth"))
        entries.push(new TableEntry("Morved"))
        entries.push(new TableEntry("Ohdru"))
        entries.push(new TableEntry("Orunu"))
        entries.push(new TableEntry("Tormud"))
        entries.push(new TableEntry("Turdoch"))
        entries.push(new TableEntry("Tsharbak"))
        entries.push(new TableEntry("Ulf"))
        entries.push(new TableEntry("Ulraigh"))
        entries.push(new TableEntry("Wartech"))
        entries.push(new TableEntry("Wladuch"))
        entries.push(new TableEntry("Wuarn"))
        entries.push(new TableEntry("Yahrad"))
        entries.push(new TableEntry("Yorged"))
        entries.push(new TableEntry("Yuchdan"))
        entries.push(new TableEntry("Yurrgold"))
        super(entries, TableTitles.BarbaricMaleName);
        this.tableType = TableType.Other;
    }
}