import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";

export class ElfenMaleNameTable extends Table {
    constructor() {
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Aelindir"));
        entries.push(new TableEntry("Alarion"));
        entries.push(new TableEntry("Alanel"));
        entries.push(new TableEntry("Albion"));
        entries.push(new TableEntry("Alirion"));
        entries.push(new TableEntry("Amariel"));
        entries.push(new TableEntry("Amaryllon"));
        entries.push(new TableEntry("Aranel"));
        entries.push(new TableEntry("Arathon"));
        entries.push(new TableEntry("Ardarell"));
        entries.push(new TableEntry("Arikarion"));
        entries.push(new TableEntry("Ariolan"));
        entries.push(new TableEntry("Avalarion"));
        entries.push(new TableEntry("Biundralar"));
        entries.push(new TableEntry("Calomiriel"));
        entries.push(new TableEntry("Ciryanil"));
        entries.push(new TableEntry("Delama"));
        entries.push(new TableEntry("Delayar"));
        entries.push(new TableEntry("Diundriel"));
        entries.push(new TableEntry("Eberon"));
        entries.push(new TableEntry("Elsurion"));
        entries.push(new TableEntry("Fälandel"));
        entries.push(new TableEntry("Fanaion"));
        entries.push(new TableEntry("Fanlön"));
        entries.push(new TableEntry("Farnion"));
        entries.push(new TableEntry("Farviriol"));
        entries.push(new TableEntry("Felerian"));
        entries.push(new TableEntry("Fäysiriel"));
        entries.push(new TableEntry("Floriel"));
        entries.push(new TableEntry("Gilion"));
        entries.push(new TableEntry("Golodion"));
        entries.push(new TableEntry("Hanyariel"));
        entries.push(new TableEntry("Ilcoron"));
        entries.push(new TableEntry("Ilmariel"));
        entries.push(new TableEntry("Imalyan"));
        entries.push(new TableEntry("Imion"));
        entries.push(new TableEntry("Imrayon"));
        entries.push(new TableEntry("Lamandrion"));
        entries.push(new TableEntry("Laryllan"));
        entries.push(new TableEntry("Lellindor"));
        entries.push(new TableEntry("Lindariel"));
        entries.push(new TableEntry("Lindion"));
        entries.push(new TableEntry("Lorindion"));
        entries.push(new TableEntry("Lorion"));
        entries.push(new TableEntry("Mandarion"));
        entries.push(new TableEntry("Mandavar"));
        entries.push(new TableEntry("Marnion"));
        entries.push(new TableEntry("Merdarion"));
        entries.push(new TableEntry("Nadyawin"));
        entries.push(new TableEntry("Navarion"));
        entries.push(new TableEntry("Nindariel"));
        entries.push(new TableEntry("Oiodin"));
        entries.push(new TableEntry("Olidir"));
        entries.push(new TableEntry("Oluvindar"));
        entries.push(new TableEntry("Ranarion"));
        entries.push(new TableEntry("Sanydriel"));
        entries.push(new TableEntry("Sanyarin"));
        entries.push(new TableEntry("Talayar"));
        entries.push(new TableEntry("Tuleirin"));
        entries.push(new TableEntry("Valandriel"));
        entries.push(new TableEntry("Valayar"));
        entries.push(new TableEntry("Varlaran"));
        entries.push(new TableEntry("Vindariel"));
        entries.push(new TableEntry("Visalyar"));
        entries.push(new TableEntry("Adernath"));
        entries.push(new TableEntry("Alaris"));
        entries.push(new TableEntry("Aldarin"));
        entries.push(new TableEntry("Amantillada"));
        entries.push(new TableEntry("Antareleon"));
        entries.push(new TableEntry("Meliodel"));
        entries.push(new TableEntry("Zerzaiol"));
        entries.push(new TableEntry("Fenvarien"));
        super(entries,
            TableTitles.ElfenMaleName);
    }
}