import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class NordicFemaleNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Akja"))
        entries.push(new TableEntry("Aeljhild"))
        entries.push(new TableEntry("Algrid"))
        entries.push(new TableEntry("Alvida"))
        entries.push(new TableEntry("Andra"))
        entries.push(new TableEntry("Anga"))
        entries.push(new TableEntry("Anhild"))
        entries.push(new TableEntry("Arva"))
        entries.push(new TableEntry("Asgerda"))
        entries.push(new TableEntry("Asgrima"))
        entries.push(new TableEntry("Askra"))
        entries.push(new TableEntry("Bornhild"))
        entries.push(new TableEntry("Bera"))
        entries.push(new TableEntry("Bjarnhilda"))
        entries.push(new TableEntry("Blodgrima"))
        entries.push(new TableEntry("Branda"))
        entries.push(new TableEntry("Bryda"))
        entries.push(new TableEntry("Eilif"))
        entries.push(new TableEntry("Eindara"))
        entries.push(new TableEntry("Eirnid"))
        entries.push(new TableEntry("Elgrima"))
        entries.push(new TableEntry("Estrid"))
        entries.push(new TableEntry("Eyvin"))
        entries.push(new TableEntry("Firunja"))
        entries.push(new TableEntry("Fjaellgard"))
        entries.push(new TableEntry("Frenja"))
        entries.push(new TableEntry("Freiya"))
        entries.push(new TableEntry("Fridgera"))
        entries.push(new TableEntry("Garhelt"))
        entries.push(new TableEntry("Garhilda"))
        entries.push(new TableEntry("Grima"))
        entries.push(new TableEntry("Gunbritt"))
        entries.push(new TableEntry("Gunda"))
        entries.push(new TableEntry("Gundrid"))
        entries.push(new TableEntry("Hallbera"))
        entries.push(new TableEntry("Hardsgera"))
        entries.push(new TableEntry("Helma"))
        entries.push(new TableEntry("Hilda"))
        entries.push(new TableEntry("Hjalda"))
        entries.push(new TableEntry("Iduna"))
        entries.push(new TableEntry("Ifirniane"))
        entries.push(new TableEntry("Ifirnslinda"))
        entries.push(new TableEntry("Linda"))
        entries.push(new TableEntry("Ingira"))
        entries.push(new TableEntry("Rötlinde"))
        entries.push(new TableEntry("Jadra"))
        entries.push(new TableEntry("Rorliffa"))
        entries.push(new TableEntry("Ragna"))
        entries.push(new TableEntry("Sigridda"))
        entries.push(new TableEntry("Sigrun"))
        entries.push(new TableEntry("Solva"))
        entries.push(new TableEntry("Solveig"))
        entries.push(new TableEntry("Swanja"))
        entries.push(new TableEntry("Thora"))
        entries.push(new TableEntry("Thordis"))
        entries.push(new TableEntry("Thorhalla"))
        entries.push(new TableEntry("Swafnild"))
        entries.push(new TableEntry("Torgrid"))
        entries.push(new TableEntry("Torlind"))
        entries.push(new TableEntry("Gardlinda"))
        super(entries, TableTitles.NordicFemaleName);
        this.tableType = TableType.Other;
    }
}