import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class RussianMaleNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Albin"))
        entries.push(new TableEntry("Anshag"))
        entries.push(new TableEntry("Arvid"))
        entries.push(new TableEntry("Baerjan"))
        entries.push(new TableEntry("Baerow"))
        entries.push(new TableEntry("Berschin"))
        entries.push(new TableEntry("Birjew"))
        entries.push(new TableEntry("Bornjeff"))
        entries.push(new TableEntry("Bosjew"))
        entries.push(new TableEntry("Boutsen"))
        entries.push(new TableEntry("Daanje"))
        entries.push(new TableEntry("Dabbert"))
        entries.push(new TableEntry("Damian"))
        entries.push(new TableEntry("Danow"))
        entries.push(new TableEntry("Duchjo"))
        entries.push(new TableEntry("Dulgjew"))
        entries.push(new TableEntry("Dunjew"))
        entries.push(new TableEntry("Dunjoscha"))
        entries.push(new TableEntry("Elko"))
        entries.push(new TableEntry("Elkwin"))
        entries.push(new TableEntry("Ertzel"))
        entries.push(new TableEntry("Fredo"))
        entries.push(new TableEntry("Galjan"))
        entries.push(new TableEntry("Goljew"))
        entries.push(new TableEntry("Grimjan"))
        entries.push(new TableEntry("Hane"))
        entries.push(new TableEntry("Helmjew"))
        entries.push(new TableEntry("Hurdo"))
        entries.push(new TableEntry("Iber"))
        entries.push(new TableEntry("Ilmin"))
        entries.push(new TableEntry("Irjan"))
        entries.push(new TableEntry("Ischtan"))
        entries.push(new TableEntry("Jaakon"))
        entries.push(new TableEntry("Jarlow"))
        entries.push(new TableEntry("Janper"))
        entries.push(new TableEntry("Joust"))
        entries.push(new TableEntry("Joschin"))
        entries.push(new TableEntry("Jucho"))
        entries.push(new TableEntry("Kolja"))
        entries.push(new TableEntry("Larjan"))
        entries.push(new TableEntry("Linjan"))
        entries.push(new TableEntry("Littjew"))
        entries.push(new TableEntry("Ljasew"))
        entries.push(new TableEntry("Ljubow"))
        entries.push(new TableEntry("Nerian"))
        entries.push(new TableEntry("Nesdan"))
        entries.push(new TableEntry("Orschwin"))
        entries.push(new TableEntry("Pjerow"))
        entries.push(new TableEntry("Oswin"))
        entries.push(new TableEntry("Panek"))
        entries.push(new TableEntry("Pedder"))
        entries.push(new TableEntry("Peraenjow"))
        entries.push(new TableEntry("Pitjow"))
        entries.push(new TableEntry("Rowin"))
        entries.push(new TableEntry("Rudjew"))
        entries.push(new TableEntry("Semkin"))
        entries.push(new TableEntry("Semkin"))
        entries.push(new TableEntry("Suschin"))
        entries.push(new TableEntry("Tannjew"))
        entries.push(new TableEntry("Thezmar"))
        entries.push(new TableEntry("Tirulf"))
        entries.push(new TableEntry("Torjin"))
        entries.push(new TableEntry("Travin"))
        entries.push(new TableEntry("Ulmjan"))
        entries.push(new TableEntry("Urnislaw"))
        entries.push(new TableEntry("Vigo"))
        entries.push(new TableEntry("Vito"))
        entries.push(new TableEntry("Wassjew"))
        entries.push(new TableEntry("Xebbert"))
        super(entries, TableTitles.RussianMaleName);
        this.tableType = TableType.Other;
    }
}