import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class SouthAmericanFemaleNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Alessandra"))
        entries.push(new TableEntry("Adaque"))
        entries.push(new TableEntry("Amira"))
        entries.push(new TableEntry("Avesandra"))
        entries.push(new TableEntry("Belatravis"))
        entries.push(new TableEntry("Baniatella"))
        entries.push(new TableEntry("Blanca"))
        entries.push(new TableEntry("Boronaya"))
        entries.push(new TableEntry("Calmora"))
        entries.push(new TableEntry("Carimina"))
        entries.push(new TableEntry("Cessandra"))
        entries.push(new TableEntry("Cessaria"))
        entries.push(new TableEntry("Consuela"))
        entries.push(new TableEntry("Cortessa"))
        entries.push(new TableEntry("Corvinida"))
        entries.push(new TableEntry("Desiderya"))
        entries.push(new TableEntry("Desmonda"))
        entries.push(new TableEntry("Diantha"))
        entries.push(new TableEntry("Dolorita"))
        entries.push(new TableEntry("Dominga"))
        entries.push(new TableEntry("Doriana"))
        entries.push(new TableEntry("Duridanya"))
        entries.push(new TableEntry("Elodia"))
        entries.push(new TableEntry("Emerencia"))
        entries.push(new TableEntry("Emilia"))
        entries.push(new TableEntry("Esmeralda"))
        entries.push(new TableEntry("Estrella"))
        entries.push(new TableEntry("Fiara"))
        entries.push(new TableEntry("Fiona"))
        entries.push(new TableEntry("Fiorella"))
        entries.push(new TableEntry("Folsina"))
        entries.push(new TableEntry("Galindia"))
        entries.push(new TableEntry("Gerlita"))
        entries.push(new TableEntry("Gilia"))
        entries.push(new TableEntry("Heliantha"))
        entries.push(new TableEntry("Hevane"))
        entries.push(new TableEntry("Imelde"))
        entries.push(new TableEntry("Imperia"))
        entries.push(new TableEntry("Inares"))
        entries.push(new TableEntry("Iunivera"))
        entries.push(new TableEntry("Ivarena"))
        entries.push(new TableEntry("Jesabela"))
        entries.push(new TableEntry("Jessande"))
        entries.push(new TableEntry("Joseda"))
        entries.push(new TableEntry("Karianna"))
        entries.push(new TableEntry("Katilinya"))
        entries.push(new TableEntry("Korrasson"))
        entries.push(new TableEntry("Leona"))
        entries.push(new TableEntry("Levita"))
        entries.push(new TableEntry("Luisina"))
        entries.push(new TableEntry("Marchesca"))
        entries.push(new TableEntry("Mercara"))
        entries.push(new TableEntry("Merida"))
        entries.push(new TableEntry("Morisca"))
        entries.push(new TableEntry("Neva"))
        entries.push(new TableEntry("Nicolasina"))
        entries.push(new TableEntry("Olea"))
        entries.push(new TableEntry("Orelia"))
        entries.push(new TableEntry("Phelicitas"))
        entries.push(new TableEntry("Phelippa"))
        entries.push(new TableEntry("Phranya"))
        entries.push(new TableEntry("Querinia"))
        entries.push(new TableEntry("Rahjade"))
        entries.push(new TableEntry("Ramira"))
        entries.push(new TableEntry("Rimiona"))
        entries.push(new TableEntry("Rosinia"))
        entries.push(new TableEntry("Sabela"))
        entries.push(new TableEntry("Salina"))
        entries.push(new TableEntry("Santilia"))
        entries.push(new TableEntry("Saranys"))
        entries.push(new TableEntry("Simiona"))
        entries.push(new TableEntry("Tomassina"))
        entries.push(new TableEntry("Ulembina"))
        entries.push(new TableEntry("Ursania"))
        entries.push(new TableEntry("Vadoria"))
        entries.push(new TableEntry("Valeria"))
        entries.push(new TableEntry("Varinella"))
        entries.push(new TableEntry("Velvenya"))
        entries.push(new TableEntry("Vida"))
        entries.push(new TableEntry("Violanda"))
        entries.push(new TableEntry("Xantilia"))
        entries.push(new TableEntry("Ximena"))
        entries.push(new TableEntry("Yvonya"))
        entries.push(new TableEntry("Zaline"))
        entries.push(new TableEntry("Zephirina"))
        entries.push(new TableEntry("Zeradia"))
        super(entries, TableTitles.SouthAmericanFemaleName);
        this.tableType = TableType.Other;
    }
}