import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class SouthAmericanMaleNameTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("Adario"))
        entries.push(new TableEntry("Agusto"))
        entries.push(new TableEntry("Alondro"))
        entries.push(new TableEntry("Alriego"))
        entries.push(new TableEntry("Alvenron"))
        entries.push(new TableEntry("Amato"))
        entries.push(new TableEntry("Amir"))
        entries.push(new TableEntry("Amirato"))
        entries.push(new TableEntry("Apreno"))
        entries.push(new TableEntry("Armado"))
        entries.push(new TableEntry("Assanto"))
        entries.push(new TableEntry("Boromeo"))
        entries.push(new TableEntry("Cascado"))
        entries.push(new TableEntry("Calmano"))
        entries.push(new TableEntry("Coragon"))
        entries.push(new TableEntry("Corvin"))
        entries.push(new TableEntry("Damiano"))
        entries.push(new TableEntry("Deredan"))
        entries.push(new TableEntry("Desiderio"))
        entries.push(new TableEntry("Diago"))
        entries.push(new TableEntry("Diamantes"))
        entries.push(new TableEntry("Dirial"))
        entries.push(new TableEntry("Domingo"))
        entries.push(new TableEntry("Dorio"))
        entries.push(new TableEntry("Efferdito"))
        entries.push(new TableEntry("Egiliano"))
        entries.push(new TableEntry("Ellio"))
        entries.push(new TableEntry("Emano"))
        entries.push(new TableEntry("Emiglio"))
        entries.push(new TableEntry("Enrisco"))
        entries.push(new TableEntry("Fiorenzo"))
        entries.push(new TableEntry("Firunando"))
        entries.push(new TableEntry("Flaminio"))
        entries.push(new TableEntry("Gaiomo"))
        entries.push(new TableEntry("Ghonzo"))
        entries.push(new TableEntry("Ghorio"))
        entries.push(new TableEntry("Gordo"))
        entries.push(new TableEntry("Hesindiego"))
        entries.push(new TableEntry("Lago"))
        entries.push(new TableEntry("Iago"))
        entries.push(new TableEntry("Imaculo"))
        entries.push(new TableEntry("Imperionso"))
        entries.push(new TableEntry("Ingarin"))
        entries.push(new TableEntry("Irato"))
        entries.push(new TableEntry("Irschan"))
        entries.push(new TableEntry("Jesidoro"))
        entries.push(new TableEntry("Kalman"))
        entries.push(new TableEntry("Kamillio"))
        entries.push(new TableEntry("Khalid"))
        entries.push(new TableEntry("lirobal"))
        entries.push(new TableEntry("Losian"))
        entries.push(new TableEntry("Lucan"))
        entries.push(new TableEntry("Lucio"))
        entries.push(new TableEntry("Luiz"))
        entries.push(new TableEntry("Mandollo"))
        entries.push(new TableEntry("Marbido"))
        entries.push(new TableEntry("Marboso"))
        entries.push(new TableEntry("Marlo"))
        entries.push(new TableEntry("Marno"))
        entries.push(new TableEntry("Massino"))
        entries.push(new TableEntry("Micirio"))
        entries.push(new TableEntry("Moralo"))
        entries.push(new TableEntry("Morisys"))
        entries.push(new TableEntry("Nestario"))
        entries.push(new TableEntry("Nostromo"))
        entries.push(new TableEntry("Nuncio"))
        entries.push(new TableEntry("Orelio"))
        entries.push(new TableEntry("Panfilo"))
        entries.push(new TableEntry("Pedresco"))
        entries.push(new TableEntry("Praiopio"))
        entries.push(new TableEntry("Quintilian"))
        entries.push(new TableEntry("Rahiano"))
        entries.push(new TableEntry("Rahjadan"))
        entries.push(new TableEntry("Ramin"))
        entries.push(new TableEntry("Ramon"))
        entries.push(new TableEntry("Rayo"))
        entries.push(new TableEntry("Romero"))
        entries.push(new TableEntry("Rondrigan"))
        entries.push(new TableEntry("Rondrigo"))
        entries.push(new TableEntry("Salpico"))
        entries.push(new TableEntry("Sandro"))
        entries.push(new TableEntry("Simodo"))
        entries.push(new TableEntry("Tarquinio"))
        entries.push(new TableEntry("Thiago"))
        entries.push(new TableEntry("Tirato"))
        entries.push(new TableEntry("Trienco"))
        entries.push(new TableEntry("Tito"))
        entries.push(new TableEntry("Ulan"))
        entries.push(new TableEntry("Unnio"))
        entries.push(new TableEntry("Vareno"))
        entries.push(new TableEntry("Vessario"))
        entries.push(new TableEntry("Vitario"))
        entries.push(new TableEntry("Vito"))
        entries.push(new TableEntry("Vittorio"))
        entries.push(new TableEntry("Wilciano"))
        entries.push(new TableEntry("Xenofero"))
        entries.push(new TableEntry("Yorge"))
        entries.push(new TableEntry("Yuan"))
        entries.push(new TableEntry("Zurbaran"))
        super(entries, TableTitles.SouthAmericanMaleName);
        this.tableType = TableType.Other;
    }
}