//https://tvtropes.org/pmwiki/pmwiki.php/Main/Conflict

import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {TableTitles} from "../tableTitles";
import {TableType} from "../tableType";

export class ConflictTropeTable extends Table{
    constructor(){
        let entries = [] as TableEntry[];
        entries.push(new TableEntry("stupidity"))
        entries.push(new TableEntry("comic con conundrum"))
        entries.push(new TableEntry("achievement through ignorance"))
        entries.push(new TableEntry("alcohol stupidity action"))
        entries.push(new TableEntry("bond villain stupidity"))
        entries.push(new TableEntry("bullying a dragon"))
        entries.push(new TableEntry("calling evil devise"))
        entries.push(new TableEntry("culture blind"))
        entries.push(new TableEntry("curiosity"))
        entries.push(new TableEntry("unnecessary robberies"))
        entries.push(new TableEntry("cutscene incompetence"))
        entries.push(new TableEntry("mery in kazadoom"))
        entries.push(new TableEntry("distress ball"))
        entries.push(new TableEntry("ditch the bodyguards"))
        entries.push(new TableEntry("dramatic slip"))
        entries.push(new TableEntry("exhaustion induced idiocy"))
        entries.push(new TableEntry("explaining the power to enemy"))
        entries.push(new TableEntry("failed a clue"))
        entries.push(new TableEntry("guns in church"))
        entries.push(new TableEntry("hand in a hole"))
        entries.push(new TableEntry("secret into the grave"))
        entries.push(new TableEntry("hero ball lawful stupid"))
        entries.push(new TableEntry("hero ball all loving hero"))
        entries.push(new TableEntry("horrible judge of character"))
        entries.push(new TableEntry("villain tells the plan"))
        entries.push(new TableEntry("MacGuffin blindness"))
        entries.push(new TableEntry("drama dream"))
        entries.push(new TableEntry("prophecy"))
        entries.push(new TableEntry("left the lifesaver behind"))
        entries.push(new TableEntry("mercy villain"))
        entries.push(new TableEntry("the idiot runes the plan"))
        entries.push(new TableEntry("bad money decision"))
        entries.push(new TableEntry("neutral female"))
        entries.push(new TableEntry("no means yes (but actually no)"))
        entries.push(new TableEntry("no peripheral vision"))
        entries.push(new TableEntry("one dimensional thinking"))
        entries.push(new TableEntry("ping pong naive"))
        entries.push(new TableEntry("recognition failure"))
        entries.push(new TableEntry("great power only for great problems"))
        entries.push(new TableEntry("reveal cover up"))
        entries.push(new TableEntry("obvious trap"))
        entries.push(new TableEntry("deal with the devil"))
        entries.push(new TableEntry("stupid surrender"))
        entries.push(new TableEntry("think smart say stupid"))
        entries.push(new TableEntry("sirene song"))
        entries.push(new TableEntry("treacherous spirit chase"))
        entries.push(new TableEntry("unusual think is ignored"))
        entries.push(new TableEntry("amnesia villain joins hero"))
        entries.push(new TableEntry("battle in the center of the mind"))
        entries.push(new TableEntry("conflicting loyalty"))
        entries.push(new TableEntry("the corruption"))
        entries.push(new TableEntry("dramatic drop"))
        entries.push(new TableEntry("dramatic sit down"))
        entries.push(new TableEntry("emotion vs stoicism"))
        entries.push(new TableEntry("fighting back is wrong"))
        entries.push(new TableEntry("gollum make me do it"))
        entries.push(new TableEntry("good angel bad angel"))
        entries.push(new TableEntry("his own worst enemy"))
        entries.push(new TableEntry("if you kill him you will be just like him"))
        entries.push(new TableEntry("i know your are there somewhere inside"))
        entries.push(new TableEntry("can't make a choice"))
        entries.push(new TableEntry("moral dilemma"))
        entries.push(new TableEntry("ordered to die"))
        entries.push(new TableEntry("personal horror"))
        entries.push(new TableEntry("secret identity problems"))
        entries.push(new TableEntry("vietnam flashbacks"))
        entries.push(new TableEntry("sour outside, sad inside"))
        entries.push(new TableEntry("split personality takeover"))
        entries.push(new TableEntry("superpowered evil side"))
        entries.push(new TableEntry("lawful or good"))
        entries.push(new TableEntry("resist inner evilness"))
        entries.push(new TableEntry("what you are in the dark"))
        super(entries, TableTitles.ConflictTrope);
        this.tableType = TableType.Other;
    }
}