export enum TableTitles {
	// Default
	Default = 'default title',

	// Character tables
	Character = 'Character',
	Gender = 'Gender',
	Race = 'Race',
	Profession = 'Profession',
	Alignment = 'Alignment',
	Motivation = 'Motivation',
	Advantages = 'Advantages',
	Disadvantages = 'Disadvantages',
	SpecialFeatures = 'Special Features',
	Curse = 'Curse',
	Nobility = 'Nobility',
	Attributes = 'Attributes',
	Attitude = 'Attitude',
	CharacterAsDevice = 'Character as Device',
	CharacterIntroduction = 'Character Introduction',
	CharacterShadowArchetype = 'Character Shadow Archetype',

	// Name tables
	GermanMaleName = 'German Male Names',
	GermanFemaleNames = 'German Female Names',

	// Animal and creature tables
	Animal = 'Animal',
	FantasyCreatures = 'Fantasy Creatures',

	// Location tables
	Location = 'Location',
	Continent = 'Continent',
	ContinentName = 'Continent Name',
	Landscape = 'Landscape',
	Building = 'Building',
	BuildingAdjective = 'Building Adjectives',
	Sphere = 'Sphere',
	Position = 'Position',
	NationName = 'Nation Name',
	NationAdjective = 'Nation Adjective',

	// Celestial tables
	WorldCreationMethod = 'World Creation Method',
	GalaxyName = 'Galaxy Name',
	GalaxyType = 'Galaxy Type',
	GalaxyImages = 'Galaxy Images',
	SpiralGalaxyImages = 'Spiral Galaxy Images',
	EclipticGalaxyImages = 'Ecliptic Galaxy Images',
	OtherGalaxyImages = 'Other Galaxy Images',
	GalaxyAnomalies = 'Galaxy Anomalies',
	SolarSystemName = 'Solar System Name',
	PlanetName = 'Planet Name',
	LivablePlanetType = 'Livable Planet Type',
	PlanetType = 'Planet Type',
	NumberOfSuns = 'Number of Suns',
	SphereName = 'Sphere Name',
	SphereNamePrefixes = 'Sphere Name Prefixes',
	SphereNameSuffixes = 'Sphere Name Suffixes',
	SphereRules = 'Sphere Rules',
	SphereConnectionName = 'Sphere Connection Name',
	UniverseName = 'Universe Name',
	UniverseNamePrefixes = 'Universe Name Prefixes',
	UniverseNameSuffixes = 'Universe Name Suffixes',
	DimensionalStructure = 'Dimensional Structure',
	FundamentalLaws = 'Fundamental Laws',
	UniverseAge = 'Universe Age',
	SectorSynonyms = 'Sector Synonyms',
	GreekLetter = 'Greek Letters',
	EnumSize = 'Enum Size',
	BlackBodyColor = 'Black Body Color',

	// Dungeon tables
	Structure = 'Structure',
	DungeonEntry = 'Dungeon Entry',
	DungeonName = 'Dungeon Name',
	DungeonType = 'Dungeon Type',
	DungeonAdjective = 'Dungeon Adjective',
	DungeonState = 'Dungeon State',
	DungeonPurpose = 'Dungeon Purpose',
	DungeonRoomArrangement = 'Dungeon Room Arrangement',
	LocationChangeEvent = 'Location Change Event',
	RealWorldDungeonName = 'Real World Dungeon Name',
	RealWorldEnemy = 'Real World Enemy',
	Furnishing = 'Furnishing',
	Obstacle = 'Obstacle',
	NaturalObstacle = 'Natural Obstacle',
	Trap = 'Trap',
	TrapTrigger = 'Trap Trigger',
	TrapFunction = 'Trap Function',
	Transition = 'Transition',
	EntranceType = 'Entrance Type',
	EntranceAdjective = 'Entrance Adjective',
	HiddenDescription = 'Hidden Description',
	TreasureContent = 'Treasure Content',

	// Artefact tables
	Artefact = 'Artefact',
	MagicalArtefact = 'Magical Artefact',
	ProfaneArtefact = 'Profane Artefact',
	Weapon = 'Weapon',
	Armor = 'Armor',
	Jewelry = 'Jewelry',
	Gemstone = 'Gemstone',
	Materials = 'Materials',
	Quality = 'Quality',
	Rarity = 'Rarity',
	Treasure = 'Treasure',
	Artwork = 'Artwork',
	ArtefactAdjective = 'Artefact Adjective',
	ObjectEnchantment = 'Object Enchantment',

	// Talent tables
	Talent = 'Talent',
	TalentCategory = 'Talent Category',
	MagicalTalent = 'Magical Talent',
	ProfaneTalent = 'Profane Talent',
	ElementalTalent = 'Elemental Talent',
	CraftTalent = 'Craft Talent',
	AthleticsTalent = 'Athletics Talent',
	ArtistTalent = 'Artistic Talent',
	TalentFromHigherPower = 'Talent From Higher Power',
	ChangeTalent = 'Change Talent',
	TargetTalent = 'Which Target of Talent',
	SummonTalent = 'Summon Talent',
	MetaMagicTalent = 'Meta Magic Talent',
	ProphecyTalent = 'Prophecy Talent',
	PsyTalent = 'Psy Talent',
	HealingTalent = 'Healing Talent',
	TimeTalent = 'Time Talent',
	TravelTalent = 'Travel Talent',

	// Monster tables
	Monster = 'Monster',
	MonsterEncounterType = 'Monster Encounter Type',
	MonsterAdjective = 'Monster Adjective',
	MonsterNumber = 'Monster Number',
	MonsterReproduction = 'Monster Reproduction',
	MonsterMeal = 'Monster Meal',

	// Town tables
	TownSize = 'Town Size',
	TownFame = 'Town Fame',
	TownEvent = 'Town Event',

	// Fraction/Nation tables
	FractionName = 'Fraction Name',
	FractionWealth = 'Fraction Wealth',
	FractionQuest = 'Fraction Quest',
	FactionFirstName = 'Faction First Name',
	FactionSecondName = 'Faction Second Name',
	FactionQuote = 'Faction Quote',
	FactionBeginningMotivation = 'Faction Beginning Motivation',

	// Adventure tables
	AdventureEvent = 'Adventure Event',
	BeginningTrope = 'Beginning Trope',
	EndingTropes = 'Ending Trope',
	InitialMeetingType = 'Initial Meeting Type',
	InitialMeetingCircumstances = 'Initial Meeting Circumstances',
	InitialMeetingTone = 'Initial Meeting Tone',

	// Culture tables
	RealCulture = 'Real Culture',

	// Other tables
	Colour = 'Colour',
	Element = 'Element',
	Emotion = 'Emotion',
	BodyParts = 'Body Parts',
	Size = 'Size',
	Senses = 'Senses',
	Weather = 'Weather',
	WeatherAdjective = 'Weather Adjective',
	NaturalEvent = 'Natural Event',
	HistoricalEvent = 'Historical Event',
	MoonPhases = 'Moon Phases',
	EpicSubstantive = 'Epic Substantive',
	Limitation = 'Limitation',
	RelationshipType = 'Relationship Type',
	Vocal = 'Vocal',
	Consonant = 'Consonant',
	SignSymbol = 'Sign Symbol',
	SignMeaning = 'Sign Meaning',
	SignForm = 'Sign Form',
	Mood = 'Mood',
	SensoryDetail = 'Sensory Detail',
	ClueSource = 'Clue Source',
	ClueObject = 'Clue Object',
	ClueConclusion = 'Clue Conclusion',
	TruthLevel = 'Truth Level',
	Age = 'Age',
	MovementType = 'Movement Type',
	Tracks = 'Tracks',
	MythicalCreature = 'Mythical Creature',
	Enemy = 'Enemy',
	BasicResource = 'Basic Resource',
	TerrainFeature = 'Terrain Feature',
	HexType = 'Hex Type',
	HexFeature = 'Hex Feature',
	HexTileHazard = 'Hex Tile Hazards',
	QuestType = 'Quest Type',
	QuestReward = 'Quest Reward',
	QuestDifficulty = 'Quest Difficulty',
	EventType = 'Event Type',
	RumorContent = 'Rumor Content',
	ProphecyText = 'Prophecy Text',
	Time = 'Time',
	IllnessType = 'Illness Type',
	IllnessSymptom = 'Illness Symptom',
	IllnessCure = 'Illness Cure',
	IllnessOrigin = 'Illness Origin',
	IllnessTransmission = 'Illness Transmission',
	IllnessWorldEffect = 'Illness World Effect',
	IllnessLore = 'Illness Lore',
	IllnessAdjective = 'Illness Adjective',
	SpellCooldown = 'Spell Cooldown',
	SpellAreaOfEffect = 'Spell Area of Effect',
	SpellPreparation = 'Spell Preparation',
	SpellLore = 'Spell Lore',
	SpellCounter = 'Spell Counter',
	Difficulty = 'Difficulty',
	Amount = 'Amount',
	PowerLevel = 'Power Level',
	Distance = 'Distance',
	GodDomain = 'God Domain',
	GodStatus = 'God Status',
	GodByname = 'God Byname',
	QuoteDisciple = 'Disciple Quote',
	QuoteCautionary = 'Cautionary Quote',
	TempleType = 'Temple Type',
	RitualTime = 'Ritual Time',
	RitualPreparation = 'Ritual Preparation',
	RitualInvocation = 'Ritual Invocation',
	RitualLocation = 'Ritual Location',
	RitualExclusiveness = 'Ritual Exclusiveness',
	RitualAction = 'Ritual Action',
	RitualOffering = 'Ritual Offering',
	RitualCulmination = 'Ritual Culmination',
	RitualFeast = 'Ritual Feast',

	// Magic System tables
	MagicAbility = 'Magic Ability',
	MagicAttribute = 'Magic Attribute',
	MagicChannel = 'Magic Channel',
	MagicCost = 'Magic Cost',
	MagicDifferentiation = 'Magic Differentiation',
	MagicEvent = 'Magic Event',
	MagicFailConsequence = 'Magic Fail Consequence',
	MagicFluff = 'Magic Fluff',
	MagicOrigin = 'Magic Origin',
	MagicRule = 'Magic Rule',
	MagicSecondLevelUse = 'Magic Second Level Use',
	MagicSource = 'Magic Source',
	MagicSpellModifier = 'Magic Spell Modifier',
	MagicSystemFantasyNameFirst = 'Magic System Fantasy Name First',
	MagicSystemFantasyNameSecond = 'Magic System Fantasy Name Second',
	MagicSystemReligionNameFirst = 'Magic System Religion Name First',
	MagicSystemReligionNameSecond = 'Magic System Religion Name Second',
	MagicSystemSciFiNameFirst = 'Magic System Sci Fi Name First',
	MagicSystemSciFiNameSecond = 'Magic System Sci Fi Name Second',
	MagicSystemWording = 'Magic System Wording',
	MagicVisual = 'Magic Visual',
	MagicWeakness = 'Magic Weakness',
	CastingMethod = 'Casting Method',

	// Other miscellaneous tables
	BalancingForTalent = 'Balancing For Talent',
	Improvement = 'Improvement',
	Knowledge = 'Knowledge',
	PowerArc = 'Power Arc',
	Prevalence = 'Prevalence',
	Quantity = 'Quantity',
	SideEffect = 'Side Effect',
	SimplifiedNpcAction = 'Simplified Npc Action',
	Transferability = 'Transferability',

	// Genre tables
	MainGenre = 'Main Genre',
	FantasySubGenre = 'Fantasy Sub-Genre',
	SciFiSubGenre = 'Sci-Fi Sub-Genre',
	HorrorSubGenre = 'Horror Sub-Genre',
	ActionSubGenre = 'Action Sub-Genre',

	// Campaign tables
	CampaignStatement = 'Campaign Statement',

	// Mythic GME tables - Core Mechanics
	MythicFateChart = 'Fate Chart',
	MythicEventFocus = 'Event Focus',
	MythicSceneAdjustment = 'Scene Adjustment',

	// Mythic GME tables - Actions
	MythicActionsTable1 = 'Actions Table 1',
	MythicActionsTable2 = 'Actions Table 2',

	// Mythic GME tables - Descriptions
	MythicDescriptionsTable1 = 'Descriptions Table 1',
	MythicDescriptionsTable2 = 'Descriptions Table 2',

	// Mythic GME tables - Core Elements
	MythicLocationsElements = 'Locations Elements',
	MythicCharactersElements = 'Characters Elements',
	MythicObjectsElements = 'Objects Elements',

	// Mythic GME tables - Character Specialized
	MythicCharacterAppearance = 'Character Appearance',
	MythicCharacterBackground = 'Character Background',
	MythicCharacterConversations = 'Character Conversations',
	MythicCharacterDescriptors = 'Character Descriptors',
	MythicCharacterIdentity = 'Character Identity',
	MythicCharacterMotivations = 'Character Motivations',
	MythicCharacterPersonality = 'Character Personality',
	MythicCharacterSkills = 'Character Skills',
	MythicCharacterTraitsFlaws = 'Character Traits & Flaws',
	MythicCharacterActionsCombat = 'Character Actions (Combat)',
	MythicCharacterActionsGeneral = 'Character Actions (General)',

	// Mythic GME tables - Location Specialized
	MythicCavernDescriptors = 'Cavern Descriptors',
	MythicCityDescriptors = 'City Descriptors',
	MythicCivilizationDescriptors = 'Civilization Descriptors',
	MythicDomicileDescriptors = 'Domicile Descriptors',
	MythicDungeonDescriptors = 'Dungeon Descriptors',
	MythicForestDescriptors = 'Forest Descriptors',
	MythicTerrainDescriptors = 'Terrain Descriptors',
	MythicWastelandDescriptors = 'Wasteland Descriptors',
	MythicStarshipDescriptors = 'Starship Descriptors',
	MythicUrbanDescriptors = 'Urban Descriptors',

	// Mythic GME tables - Creature Specialized
	MythicAnimalActions = 'Animal Actions',
	MythicCreatureDescriptors = 'Creature Descriptors',
	MythicUndeadDescriptors = 'Undead Descriptors',
	MythicAlienSpeciesDescriptors = 'Alien Species Descriptors',

	// Mythic GME tables - Military & Objects
	MythicArmyDescriptors = 'Army Descriptors',
	MythicMagicItemDescriptors = 'Magic Item Descriptors',
	MythicMutationDescriptors = 'Mutation Descriptors',

	// Mythic GME tables - Meta/Narrative
	MythicAdventureTone = 'Adventure Tone',
	MythicPlotTwists = 'Plot Twists',

	// Auto-added missing titles
	AdventureBeginning = 'Adventure Beginning',
	AdventureClimax = 'Adventure Climax',
	AdventureFinal = 'Adventure Final',
	AdventureRising = 'Adventure Rising',
	AfricanName = 'African Name',
	ArabicFemaleLastName = 'Arabic Female Last Name',
	ArabicFemaleName = 'Arabic Female Name',
	ArabicFemaleNameAddition = 'Arabic Female Name Addition',
	ArabicMaleLastName = 'Arabic Male Last Name',
	ArabicMaleName = 'Arabic Male Name',
	ArabicMaleNameAddition = 'Arabic Male Name Addition',
	BarbaricFemaleName = 'Barbaric Female Name',
	BarbaricLastName = 'Barbaric Last Name',
	BarbaricMaleName = 'Barbaric Male Name',
	BarbaricNickName = 'Barbaric Nick Name',
	ConflictTrope = 'Conflict Trope',
	ElfenFemaleName = 'Elfen Female Name',
	ElfenMaleName = 'Elfen Male Name',
	FrenchFemaleName = 'French Female Name',
	FrenchLastName = 'French Last Name',
	FrenchMaleName = 'French Male Name',
	FrenchPlaceNameTable = 'French Place Name Table',
	GreekFemaleName = 'Greek Female Name',
	GreekLastName = 'Greek Last Name',
	GreekMaleName = 'Greek Male Name',
	IndianFemaleName = 'Indian Female Name',
	IndianMaleName = 'Indian Male Name',
	NationRelationship = 'Nation Relationship',
	NordicFemaleLastName = 'Nordic Female Last Name',
	NordicFemaleName = 'Nordic Female Name',
	NordicMaleLastName = 'Nordic Male Last Name',
	NordicMaleName = 'Nordic Male Name',
	PlotTrope = 'Plot Trope',
	RulerNicknames = 'Ruler Nicknames',
	RussianFemaleName = 'Russian Female Name',
	RussianLastName = 'Russian Last Name',
	RussianMaleName = 'Russian Male Name',
	SouthAmericanFemaleName = 'South American Female Name',
	SouthAmericanLastName = 'South American Last Name',
	SouthAmericanMaleName = 'South American Male Name',
	TransitionAdjective = 'Transition Adjective',
	VillainAdjective = 'Villain Adjective',
}
