import { Table } from '../table';
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';

export const dungeonConditions: string[] = [
	'damp',
	'flooded',
	'crumbling',
	'overgrown',
	'dusty',
	'moldy',
	'smoky',
	'polluted',
	'toxic',
	'enchanted',
	'haunted',
	'sacrosanct',
	'forbidden',
	'guarded',
	'trapped',
	'mirrored',
	'warped',
	'shifting',
	'collapsing',
	'infested',
	'consecrated',
	'desecrated',
	'silent',
	'echoing',
	'scorched',
	'frozen',
	'corrupted',
	'sanctified',
	'illuminated',
	'darkened',
	'sealed',
	'open',
	'ventilated',
	'stifling',
	'hallowed',
	'unstable',
	'restored',
	'ruined',
	'invisible',
	'magical',
	'surreal',
	'animated',
	'sterile',
	'vibrant',
	'decrepit',
	'pristine',
	'barred',
	'obscured',
	'radiant',
	'gloomy',
	'luminous',
	'arid',
	'humid',
	'stagnant',
	'whispering',
	'quiet',
	'turbulent',
	'intact',
	'dilapidated',
	'fortified',
	'enchanted',
	'mystical',
	'arcane',
	'divine',
	'profane',
	'blighted',
	'inviting',
	'repelling',
	'contaminated',
	'hazy',
	'foggy',
	'ethereal',
	'oppressive',
	'liberated',
	'exalted',
	'dim',
	'bright',
	'shadowy',
	'blessed',
	'cursed',
	'reverberating',
	'soundless',
	'parched',
	'lush',
	'treacherous',
	'secure',
	'sacred',
	'profaned',
	'sullied',
	'revered',
	'defiled'
];

export class DungeonStateTable extends Table {
	constructor() {
		let entries = [] as TableEntry[];
		for (let condition of dungeonConditions) {
			entries.push(new TableEntry(condition));
		}
		super(entries, TableTitles.DungeonState);
	}
}
