import { Table } from '../table'
import { TableType } from '../tableType';;
import { TableEntry } from '../tableEntry';
import { TableTitles } from '../tableTitles';

export const dungeonAdjectives: string[] = [
	'abandoned',
	'ancient',
	'arcane',
	'barren',
	'bewitched',
	'blighted',
	'buried',
	'cavernous',
	'chaotic',
	'cursed',
	'decayed',
	'derelict',
	'desolate',
	'dismal',
	'echoing',
	'eldritch',
	'enchanted',
	'entangled',
	'forgotten',
	'forsaken',
	'frozen',
	'ghoulish',
	'gloomy',
	'haunted',
	'hidden',
	'icy',
	'infested',
	'lost',
	'luminous',
	'malignant',
	'misty',
	'mysterious',
	'ominous',
	'perilous',
	'primeval',
	'ruined',
	'sacred',
	'savage',
	'shadowy',
	'shifting',
	'silent',
	'sinister',
	'skeletal',
	'stagnant',
	'subterranean',
	'sunken',
	'tainted',
	'timeless',
	'treacherous',
	'twisted',
	'unhallowed',
	'veiled',
	'vile',
	'whispering',
	'withered',
	'wraithlike',
	'abysmal',
	'clandestine',
	'cryptic',
	'dank',
	'effulgent',
	'eldritch',
	'forlorn',
	'glacial',
	'harsh',
	'impenetrable',
	'incandescent',
	'inviolate',
	'labyrinthine',
	'malevolent',
	'nefarious',
	'obsidian',
	'opulent',
	'palatial',
	'phantasmal',
	'primal',
	'recondite',
	'sepulchral',
	'serpentine',
	'shrouded',
	'sylvan',
	'tenebrous',
	'torrid',
	'unearthly',
	'virulent',
	'wasted',
	'zephyrian'
];

export class DungeonAdjectiveTable extends Table {
	constructor() {
		let entries = [] as TableEntry[];
		for (let adjective of dungeonAdjectives) {
			entries.push(new TableEntry(adjective));
		}
		super(entries, TableTitles.DungeonAdjective, TableType.Dungeon);
	}
}
